### ISSUE TITLE
Refactoring aqt

### ISSUE THREAD

**Issue by RumovZ** [ankitects/anki#1013]
Background (completely redundant, actually 🙂)
---
Currently, I'm implementing a feature in the browser to toggle between displaying cards and notes in the table. I got it to work passably but it was messy adding an if-else clause in every other method. So I went ahead and refactored the whole table view in a new class which takes care of all the model, header and (the newly added) state business.
Needless to say, that broke all kinds of other parts which rely on accessing the browser's fields (and fields of fields and so on) directly and they will need to be updated accordingly.
The project started out as an experiment, but now that it's not only working but also a major improvement in terms of code quality I'm wondering if there's any chance for it to be integrated into the main branch.

---
I've mostly read about moving pylib code into rslib, but what is your position regarding refactoring the aqt part? As an example,  I would split a code monster like the browser into multiple submodules consisting of self-contained classes with strictly defined interfaces only accessing methods, not fields, of each other.
Obviously, that would be a quite an add-on killer, but once those are updated to use the proper access functions, it would save both core and add-on developers a tremendous amount of time that is currently wasted on understanding the code, legacy support and fixing things that broke by changing something seemingly completely unrelated.

**Comment by dae** [comment]
There is a lot of code in aqt I'd love to rewrite, but I think we need to be careful how much we change in a certain space of time, as if we break too much too quickly, and don't offer compelling reasons to update (eg new functionality that will benefit a lot of users), then we risk users not wanting to update. 2.1.41 has already broken a fair bit, and I think we'll need some time for those changes to settle down and the popular add-ons to catch up.

I'd also like to get the remaining pylib/rslib work (particularly scheduling & import/export) done soon - I'd wanted it done before the end of 2020, but things have kept cropping up. AnkiDroid has an early integration with rslib in alpha at the moment, and if that's successful, changes in rslib will basically benefit all three platforms at once.

Before we go crazy refactoring aqt, it's also worth spending a bit more time looking into how feasible it would be to implement more of the UI in HTML/JS. The browse screen's performance can be quite bad when users have a lot of columns activated on a large display, and especially when they contain a non-trivial amount of text. Qt's MVC model requires frequent calls into Python which is slow, and Qt's font rendering can become very slow when fed larger amounts of text, even if it only will end up showing the first 10-20  characters of it due to the column sizing. I whipped up a very basic prototype about a year ago that seemed to perform well, but then put it on the backburner and haven't had a chance to return to it yet. It would be a large undertaking, and would break anything that touched the browser, so we'd probably be better off starting smaller with other peripheral features first, before deciding whether to go down that path or not.

**Comment by RumovZ** [comment]
I see, that's good to know. I definitely got frustrated with Qt's underperformance in the past, especially with the selection model. It seems reasonable to postpone structural changes to aqt until the other big refactorings are done, then.

I'll investigate if I can implement the notes view nicely without too much breakage. Even if a PR would have to sustain most of the existing issues, making the table view more self-sufficient should come in handy for the future plans as well.
