### ISSUE TITLE
Unexpected non breaking space inserted after using mathjax or latex shortcuts in editor

### ISSUE THREAD

**Issue by sandersantema** [ankitects/anki#1053]
I ran across this problem yesterday when find and replace did work for some cards and not for others, all seemingly the same. I've tested this using the latest git version at the time of writing: `3ba08d1189999c38f983288e980f39494c1c0057`using the `--safemode` commandline switch and encountered the problem on the latest beta too.
What happens is the following:

When adding a formula using the `Ctrl-M + M` shortcut (to be exact adding a space and then using the shortcut) and all other latex/ mathjax shortcuts to the following piece of text (where foo is followed by a space):
```html
foo
```

It becomes:
```html
foo&nbsp;\(\)
```

As far as I'm able to discern there's no reason for a non breaking space to be inserted, I couldn't find any reference to it in `editor.py` and if the text preceding the formula is long enough the formula gets put on a newline anyways as can be seen here:
![image](https://user-images.githubusercontent.com/21057514/110206605-041eb600-7e7f-11eb-8cac-9c31adf4bc6c.png)

The text of the card seen in the screenshot is:
```html
foofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoo&nbsp;\(\sum^{\infty}_{k = 0}{x^k}\)
```

On the other hand it is quite confusing when using search and replace which won't work if matching on a space while there's a non breaking one instead. So I think this is a bug and the space shouldn't be replaced by a non breaking space.

**Comment by sandersantema** [comment]
I've narrowed it down to the `wrapInternal` function in `ts/editor/wrap.ts` namely the else-clause which is triggered when `plainText` is false, if `plainText` is unconditionally set to true and the else-clause therefore never used no unexpected non breaking space is inserted.

**Comment by sandersantema** [comment]
It seems to be a problem not with code of Anki itself but rather the `execCommand` function which as described [here](https://w3c.github.io/editing/docs/execCommand/#canonical-space-sequences) inserts non breaking spaces to prevent multiple spaces from collapsing like they normally would. However in my example only one case follows foo, i.e. `foo `, which doesn't collapse anyway and therefore doesn't need a non breaking space inserted.

**Comment by dae** [comment]
We're relying on the contentEditable support in the browser to handle this. Do you have any suggestions on how this could be solved in a way that doesn't complicate the code and doesn't risk breaking other things?

**Comment by sandersantema** [comment]
I don't think there actually is having thought about it a bit. I'm certainly no expert (as I'd never heard of contentEditable before looking into this) but it seems like there's not anything short of completely replacing contentEditable which would actually fix this and therefore nothing which wouldn't require a considerable amount of effort. Although it might still be a good goal for the future given that it seems contentEditable is being deprecated. 

One hacky fix/ workaround would be a setting allowing the user to switch on a switch in the search and replace window which would interpret every space as either an actual space or a non breaking one i.e. ` ` as ` |(?:&nsbp;)`(I believe that's the right regex for a space or `&nsbp;` in a non capturing group). But this is obviously not a fix and quite a bad workaround in various ways.

**Comment by dae** [comment]
Ok, I think I'll close this for now if there's nothing actionable we can practically do.

**Comment by huttarl** [comment]
I realize that this issue is closed, and for very understandable reasons -- it would take a lot of work to replace contentEditable and execCommand(), which make some very messing (though understandable) compromises, in a way that didn't break a lot of stuff. However, as @sandersantema says, "It might still be a good goal for the future given that it seems contentEditable is being deprecated."

So I'll just record my +1 here. Whenever I copy and paste HTML into an Anki note, many of the spaces get automatically and invisibly replaced by &nbsp; (see [https://w3c.github.io/editing/docs/execCommand/#canonical-space-sequences](url) for why). Sometimes this happens around MathJax expressions, but other times it's non-math text from Wikipedia, or even when I'm just _typing_ a space after a word that's in bold. This means that line wrapping is messed up in many places, but I often don't notice that problem until I later drill on the cards, at which point I have to try to go back and fix the problem, possibly on a mobile device, where search-and-replace is not available.

One suggestion would be a setting (whose default preserves the status quo, so that we don't break anything for anyone who doesn't opt in) to just automatically convert all &nbsp; to normal spaces after each edit. Yes, that sounds like overkill, and it wouldn't be the right choice for everybody. But it would be relatively simple to implement, because it doesn't require replacing the behavior of contentEditable.execCommand() (it would be done afterward). And for people like me, who very rarely want a non-breaking space, and who spend a lot of time removing them, it would be a big win. For the very rare case where a non-breaking space is wanted, one could manually insert &#xa0; (that is, &nbsp; written using a numeric character reference so that it didn't get automatically converted to a space).

Thank you, developers, for all your work on Anki -- it's a great benefit to me and several of my family members!

**Comment by virginviolet** [comment]
I'm a perfectionist working on a large collection and these non-breaking space parasites eat my time. And are so annoying.

If a space is at the end of the text field, it uses non-breaking space. Makes sense, I guess. When you type a new character, it replaces that trailing NBSP with a normal space. All good. But if you paste text instead of typing by hand, it doesn't replace the non-breaking space.
A workaround is to type a period before you paste anything, then press the ← key. Then it won't add non-breaking spaces because it's not the end of the text. However, even with this method, it also always uses NBSP before and after a hyperlink, even replacing normal spaces with NBSPs.

There is [nbspRemover](https://ankiweb.net/shared/info/1676672391), but the latest review says it's not working. And I still want to be able to manually place NBSPs.

Would be great if you could do something like what @huttarl suggested.

**Comment by huttarl** [comment]
@virginviolet nbspRemover has apparently been fixed by Shige: https://ankiweb.net/shared/info/1998029342
I haven't tested this fix, but it may do what we need.
