### ISSUE TITLE
In browser, the deck tree's arrow open the deck

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankitects/anki#1059]
2.1.41 beta 7
Previously, in the deck browser, in the left pannel, when you click on an arrow near a deck name, it opened/closed the list of subdeck and that's it.
Now it also show the deck content. I believe it is a bug and should be reversed. Indeed:
* It loses current selection and search result and search bar content while I did not expected it too
* Loading a big deck takes 5 seconds on my computer. This totally stop the interaction and forbids to close everything/open every subdeck until I find the one I'm looking for.

**Comment by RumovZ** [comment]
> Previously

Any specific version? I can see that for some reason, 2.1.40 used the current index whereas 2.1.41 uses the index at mouse position. So if you don't have a current element (especially just after opening the browser), you would achieve the desired behaviour then, but not now.

**Comment by BlueGreenMagick** [comment]
#1035 
The problem here is that clicking the little arrow triggers click event.
* When we used currentIndex find SidebarItem to run on_click, because currentIndex wasn't changed when the little arrow was clicked, it would seem as the click did not happen (even though it did). However, clicking completely elsewhere can also trigger click event on currentIndex SidebarItem.
* If we use mouse position to find out (as we do now), the little arrow is thought of as part of the SidebarItem next to it. 

If possible, it would be ideal to not trigger the click function at all.

**Comment by Arthur-Milchior** [comment]
Thanks a lot. Really appreciate not to have to look at qt myself and have this gone

**Comment by RumovZ** [comment]
That's the very same workaround I implemented in my [PR](https://github.com/ankitects/anki/pull/1044/commits/9a844591feffbd103281209b851b01b4d1cc4fbc). 🙂 
To check for equality there can't hurt, however, it will still trigger the click event if the current element is the one being expanded. 
I guess we could abuse the expansion signal to make it work in this case, too. But that would only work properly if we switched the click event to work with mouse button press as well (currently it's triggered on release).
