### ISSUE TITLE
Anki 2.1.41 won't start. "Could not load the Qt platform plugin "xcb" in "" even though it was found."

### ISSUE THREAD

**Issue by ElnuDev** [ankitects/anki#1061]
I've just installed Anki 2.1.41 from the Linux release file on GitHub on my laptop, and I'm having an issue that it doesn't start up at all. (It installed just fine on my main machine, which is running the exact same OS, Pop!_OS 20.10.)

I tried running Anki from the command line using `anki` to see if it would give any errors, and this is what it said:

```
Qt info: Could not load the Qt platform plugin "xcb" in "" even though it was found. 
Qt fatal: This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.
 
Aborted (core dumped)
```

What should I do? Is there some Qt package that I need to install to get it working? `install.sh` should probably ensure that all the right packages are installed, so I guess it's a bug.

**Comment by dae** [comment]
Please see https://forums.ankiweb.net/t/anki-not-starting-on-linux-error-loading-software-graphics-driver/6603, and start a new thread over there with the debug output if you're unable to resolve the issue.

**Comment by goduck777** [comment]
I request to reopen this ticket. Currently native wayland support is disabled on Anki, but running in xwayland can cause other issues on wayland platform such as blurring in HiDPI, which does not have a solution yet.

Actually Qt and PyQt have native wayland support. The reason that the release package cannot run in wayland natively before is because some files of Qt5 on wayland support is missing from the package. I found that by including these files, the release Anki can run natively in wayland

anki/bin/PyQt5/Qt/plugins/wayland-shell-integration
anki/bin/PyQt5/Qt/plugins/wayland-decoration-client
anki/bin/PyQt5/Qt/plugins/wayland-graphics-integration-client

So please just add these files manually or change the packaging script to include them.
