### ISSUE TITLE
update manual to reflect changes in 2.1 scheduler

### ISSUE THREAD

**Issue by dae** [ankitects/anki#1073]
https://forums.ankiweb.net/t/i-have-a-hard-button-on-my-new-cards-1-1hr-beginner/8374

**Comment by missy-davies** [comment]
I'm replying to [this](https://forums.ankiweb.net/t/a-thank-you-newcomer-contributions-to-the-manual/8885) discussion to have everything about this issue in a central place.

> As of Anki 2.1.41, users are prompted to update to the 2.1 scheduler on startup, so ensuring the changes covered on The Anki 2.1 scheduler - Frequently Asked Questions 2 are described in the manual would be appreciated - what springs to mind in particular are the number of buttons when learning, and the way things like learning cards are treated in filtered decks.

It looks like the manual already has updates regarding the 4th new 'Hard' button. For example, I noticed [here](https://docs.ankiweb.net/#/studying?id=reviewing) mentions the Hard button and [here](https://docs.ankiweb.net/#/studying?id=keyboard-shortcuts) mentions to use keyboard shortcuts 1-4.

Was there another section I'm missing that should mention the 4 buttons or the Hard button specifically? 

In the meantime, I looked at the rest of the scheduler changes and I submitted a first small [pull request](https://github.com/ankitects/anki-manual/pull/51) about the behaviour of suspended/buried cards. If this looks ok, then I can continue updating the manual with the other functionality covered in the change notes, starting with the filtered decks which should be a more involved update.

**Comment by missy-davies** [comment]
UPDATE: I had a bit of extra time and added in another [small pull request](https://github.com/ankitects/anki-manual/pull/52) to update the Studying > Decks section on info about subdecks as well!

**Comment by missy-davies** [comment]
Another update from me, I've worked through the rest of the changes in [this article](https://faqs.ankiweb.net/the-anki-2.1-scheduler.html) to update the manual. This is the [relevant pull request](https://github.com/ankitects/anki-manual/pull/53). 

The only things left to add regarding the changes from the 2.1 scheduler are these bullet points: 
- "Lapsed reviews have their next due date updated on the last relearning step, instead of the first step."
- "There is a new option in the preferences screen to show day learning cards before reviews."

I wasn't sure what the first meant, and I couldn't find the setting on my Anki for the second, so I didn't feel comfortable updating the manual with that information. 

Any direction would be appreciated, otherwise, I can leave this bit for someone else!

**Comment by dae** [comment]
The time when lapses were applied was not documented in the past (it's more an implementation detail), so we can skip documenting that.  The option is the bottom one in this screenshot - "larger steps" means inter-day learning cards (ones that cross a day boundary):

<img width="563" alt="Screen Shot 2021-04-14 at 11 16 48 am" src="https://user-images.githubusercontent.com/180542/114640228-f88e9c80-9d12-11eb-8303-6b89064f61f6.png">

**Comment by missy-davies** [comment]
Ok thanks, in that case, it looks like that bit has already been adequately documented in the preferences > scheduling section! 

This issue should be good to close!
