### ISSUE TITLE
add a firstreview:x search that matches cards introduced for the first time in x days?

### ISSUE THREAD

**Issue by dae** [ankitects/anki#1093]
The information is not directly available to us in the revlog unfortunately, so it would mean looking for cards that have their first revlog entry within the provided timeframe.

Better suggestions on naming welcome too.

https://forums.ankiweb.net/t/browser-show-how-many-cards-i-suspended-today/8578/6

**Comment by dae** [comment]
@RumovZ if this interests you, please feel free to pick this one up when you have a chance. Maybe firstrated? firstanswer:? Open to suggestions.

**Comment by RumovZ** [comment]
Will definitely look into it once I have the deck name sorted out.
I think `firstrated` would be the most intuitive as we already have `rated`. But I would prefer a single, unique word like `introduced` because it's easier to read and remember. I like `introduced` because it conveys the meaning of the first review to the scheduler (the card left the new queue) but it's a bit long.

**Comment by dae** [comment]
I don't have a strong preference, and we can always change it later
