### ISSUE TITLE
Automatically switch to night mode when dark theme in use on Linux

### ISSUE THREAD

**Issue by VikoRifeo** [ankitects/anki#1116]
![image](https://user-images.githubusercontent.com/13078933/114104356-f0081300-9887-11eb-863b-1d594ed92072.png)

As you can see, the text is still rendered in black even in dark mode, rendering it very difficult (though not impossible) to read. Every screen I've checked is at least in part rendered this way. I don't know if this happens on other DEs, but I'm using KDE on Arch Linux. Anki 2.1.43, Qt 5.15.2, PyQt 5.15.4.

**Comment by Meretan** [comment]
Try set Nigth mode in tools -> Configs -> Night Mode

"Night" may be "Dark", "Configs" may be "Setup" (not sure cause using Russian version)

**Comment by VikoRifeo** [comment]
That works, thank you, but it ought to sync with the desktop theme.

**Comment by dae** [comment]
Maybe this could be accomplished by inspecting the standard colour palette - a pull request would be welcome!

**Comment by kitmonisit** [comment]
@Meretan what you mentioned only affects the cards, not the UI.

@dae I think I can work on this. Would you mind pointing me to where in the code the text and colors are specified? That way, I can start quickly without having to sift through the codebase. I'd really appreciate it.

**Comment by dae** [comment]
setupStyle() in main.py is where the preference is loaded. In order to ensure the UI in the preferences matches the current state though, it may make sense to explicitly enable the preference when a dark theme is detected on Linux, and not just adjust the value that is set on theme_manager.

**Comment by kitmonisit** [comment]
Thank you @dae! This should make a good starting point. I can work with Python fairly well, but querying the Linux desktop environment or window manager is totally new to me.

@VikoRifeo I am using BunsenLabs Linux, with Openbox window manager. I see mentions of GTK here and there when dealing with UI appearance.

**Comment by dae** [comment]
You may be able to use QPalette to determine if the window background is darker than the text foreground. Combined with a gate on 'isLin', it shouldn't require changing many lines of code

**Comment by dareducky** [comment]
I was about to open an issue connected to this one but, maybe, the scope of this issue could be expanded a bit?

I would love to have an auto dark mode based on Windows dark theme, similar to Firefox. I have a task schedule to put my windows machine to dark mode at 7pm and everything is dark except anki.

Conversely, I would be completely satisfied if I could open anki with a dark theme flag (if it's easier to implement instead of detecting the system ui).

Right now, setting anki to dark theme is a quite convoluted process where you first need to open -> go to settings -> set dark theme -> restart anki.

The ideal workflow would be (any of those):

1. Anki detect the system theme;
2. A setting on anki to automatic change theme based on time of day;
3. A flag to open anki in dark mode: "anki.exe --dark-theme" or similar.

**Comment by dae** [comment]
An auto mode is of limited usefulness if it only applies on startup, and being able to update the UI dynamically will require a fair bit of work. A env var that controls the theme used at startup (and perhaps sets the config at the same time, so that the prefs screen shows the correct thing) should be fairly easy to add - happy to accept a PR to that effect.

**Comment by johncoxon** [comment]
Just to chip in as a Mac user, I'd also really like this to be able to work based on Mac dark theme, too.

It shouldn't be difficult to detect the theme that's in use at startup, I'm using <a href="https://github.com/albertosottile/darkdetect">darkdetect</a> to do it for my Anki dark mode add-on, but my add-on really isn't perfect and having this baked into Anki directly would be amazing.

**Comment by mizzunet** [comment]
Anki Version 2.1.15 (442df9d6)
Qt 5.15.2 PyQt 5.15.2
Debian 11 KDE

![Screenshot_20210921_222017](https://user-images.githubusercontent.com/10193999/134214421-794b3cd3-bae0-409c-98bd-30f44335a566.png)
This error persisits

**Comment by hpfr** [comment]
This should probably be split into two issues, because they'll probably require different fixes. The issues:
- fix the static black text and icons across the application (see the screenshot in the original post)
- make "Show **cards** as white on black (night mode)" option automatic based on operating system (or Qt) theming

I'm being specific with the latter request because it's being called "night mode" here, but it should be noted that (as I understand it) this "night mode" Anki setting only affects how cards are rendered, not the application UI. Most of the application UI is already automatic, except for some text and icons. I only have experience with Linux, though. Maybe Windows or macOS just load it with full light theme? That's probably an issue with Qt or PyQt, then, because if you set a dark theme in your Linux desktop environment, most of the app is dark.

The automatic card style switching would be a nice feature to have, but the former "hardcoded" black elements are a pretty significant bug, I think. It feels very anachronistic, and for first-time users (on Linux, at least, maybe Windows as well?) it is very disorienting to have the main page of the app be immediately unreadable. I'm a huge fan of Anki, so it's concerning to think people might not be able to use it because of this issue.

@dae is there any way for those of us concerned about the former readability issue to raise its priority on your todo list :sweat_smile:? Anki is the only (currently maintained) application I use that still has static black elements that break the app for dark theme users. Can we make a bounty or something? Thanks for your work on Anki.

To work around the static black elements bug on Linux, you can run Anki using `QT_STYLE_OVERRIDE=adwaita anki` to force light theme. It's definitely not ideal, but at least the application can be used, then.

**Comment by dae** [comment]
People using a dark mode theme can already resolve the issue by turning on night mode in Anki's preference screen. This issue is requesting Anki do it automatically, which would be nice, but is not the most pressing thing at the moment.

**Comment by StanczakDominik** [comment]
I'd just like to express the joy of seeing this implemented. Thanks, @dae! :)

**Comment by dae** [comment]
Thanks also go to @RumovZ who did some of the groundwork to make this possible

**Comment by PxBCPG** [comment]
a must have feature for macOS user, when every app are changing their theme at the same time, and there is still Anki with it Light Mode...

**Comment by johncoxon** [comment]
I believe the code that fixes this from #1471 is now live in Anki 2.1.52 and it works like a dream, thanks to @dae and everyone else who did sterling work here!
