### ISSUE TITLE
customizable replacements in TTS filters

### ISSUE THREAD

**Issue by dae** [ankitects/anki#1171]
https://forums.ankiweb.net/t/ankimobile-tts-reading-cloze-as-blank/4241/5

I can think of two possibilities:

- storing a dict of replacement in the collection config of the form {"...": "blank"}. Would case-insensitive matches be sufficient, or do we need to support regexs?
- requiring the user to specify the replacements in the tts tag

The former is probably more user-friendly.

**Comment by RumovZ** [comment]
As I understand it, the user was using the Ankidroid feature to read out the front- and backsides of flashcards, where the voice is pronouncing deleted clozes as "blank". He now is on AnkiMobile where this feature also exists but deleted clozes aren't pronounced at all. Is that correct?
If it is, I don't see how this is related to TTS filters. Isn't it only relevant to the read-aloud option, which doesn't exist on desktop?
What other use cases do you have in mind for the replacement dict apart from enunciating deleted clozes?

**Comment by dae** [comment]
The computer version supports TTS too:

https://docs.ankiweb.net/templates/fields.html#text-to-speech

The filter applies some transforms to the text, and it's then read on the frontend and fed to the TTS engine. So if we handle this at the filter level, it shouldn't require updating the UI end.

... → "blank" would be the main one, so we could just special-case that. I thought there may be people who won't like "blank" though, and exposing the ability to specify transforms would allow users to choose which replacements were made.

**Comment by RumovZ** [comment]
But the computer TTS can only read out fields, not whole sides, can it?
Say we take the default cloze notetype with `{{cloze:Text}}`  on the frontside, and we have a note where the content of "Text" is
> Paris is the capital of {{c1::France::country}}.

Then we only have two options:

1. `{{tts en_US:Text}}` would be nonsensical, the voice would say something like "Paris is the capital of cee-one-France-country".
1. `{{tts en_US:cloze-only:Text}}` would only read out "country".

But what the user actually wants is "Paris is the capital of blank" or "Paris is the capital of country", so he can answer the card without looking at it.

Even if a filter to replace "[...]" with "blank" was available, it wouldn't help, since the replacement doesn't need to be made inside a field, but after the card side has been rendered to something like "France is the capital of [...]."

Am I missing something?

**Comment by dae** [comment]
Filters can be chained, so you can use the normal cloze filter instead of the cloze-only one:

{{tts en_US:cloze:Text}}

**Comment by RumovZ** [comment]
Ah, sorry, I didn't think of that. I was thrown off by the auto TTS option on Ankidroid.
In that case, I would only modify the TTS to replace "[...]" with "blank" (or a localisation). If the user doesn't like the sound of it, he can already specify an arbitrary expression to be read instead:
> Paris is the capital of {{c1::France::dot dot dot}}.

I would also implement custom replacements, if you think that's necessary. But it would help to know what the use cases would be.

**Comment by dae** [comment]
Requiring the user to update all the clozes in their collection to get a different reading isn't great :-) But maybe it's something people won't feel the need to customize. We can definitely start with just ..., and wait to see if there's demand for anything else before we proceed further - your YAGNI instinct here is probably a good thing
