### ISSUE TITLE
keyboard shortcuts for bullets/numbers/indent

### ISSUE THREAD

**Issue by dae** [ankitects/anki#1473]
https://forums.ankiweb.net/t/shortcuts-for-starting-bulleted-numbered-list-increasing-decreasing-indent/14572

**Comment by kleinerpirat** [comment]
Here's what would feel the most intuitive to me:
- while in a list (i.e. one of the list buttons is active), `Tab` indents and `Shift+Tab` outdents the current item
  - when the item is maximally outdented, `Shift+Tab` brings you to the previous field
- `Enter` on an empty list item moves the cursor outside the list and deletes that empty item
  - To tab out of a field, you'd hit `Enter` twice to get out the list and then hit `Tab` to switch fields.

That's the list editing behaviour everyone knows from Word etc., and it still allows for keyboard-only editing.

**Comment by hgiesel** [comment]
Not sure about Tab. If at some point we allow indenting paragraphs (normal text), we'd have problems with <kbd>Tab</kbd>.
Another option would be to Ctrl+[ and Ctrl+].

**Comment by dae** [comment]
Yeah, I'm not sure overriding tab there is the best idea. Users are used to using Tab to switch between fields, and making it behave differently depending on where the cursor is would probably cause frustration.

**Comment by jonasfagerlund** [comment]
Bear notes use:

⌘L - Unordered list
⇧⌘L - Ordered list

Might be an option.

**Comment by dae** [comment]
That'll conflict with the card layout button

**Comment by TessTrella** [comment]
Is it possible to make the keyboard shortcuts configurable by the user?
If people are using Anki to study a foreign language, the more shortcuts you add, the more likely they will interfere with an existing key binding.
(For example, I just upgraded to Version ⁨2.1.49 (dc80804a)⁩, and now I'm no longer able to type certain characters in French because of a conflicting shortcut.)
I'm not familiar with the codebase, so I'm not sure how difficult it would be to allow configuration of the shortcuts.

**Comment by dae** [comment]
It's not trivial, but may come at one point. In the mean time the conflict will be addressed on Anki's end: https://forums.ankiweb.net/t/option-i-shortcut-conflicts-with-language-input/15206
