### ISSUE TITLE
Webview regressions

### ISSUE THREAD

**Issue by RumovZ** [ankitects/anki#1516]
The webviews look mostly great now and there don't seem to be any WIPs right now, so I've collected some regressions (and nitpicks 🙂) here. I didn't try to make PRs, because I'd likely make things worse for other platforms and devices.
@hgiesel @kleinerpirat 

General
---
- [x] Nightmode scrollbars have gone. (Replaced by lightmode scrollbars.)

Deck Options
---
- [x] 1-px top margin (Change notetype window on the right for comparison)
![grafik](https://user-images.githubusercontent.com/48286681/144215825-867d7d71-f18a-49a2-a9ad-c559bfa975e0.png) ![grafik](https://user-images.githubusercontent.com/48286681/144215923-a4535be6-4535-464d-9553-b35775b4f064.png)

Change Notetype
---
- [x] (More of a question) What is the reason for the background box? Looks quite different than other dialogs.
- [x] Name of target notetype is cut off at the bottom. ("g"s, "j"s, etc.)
![grafik](https://user-images.githubusercontent.com/48286681/144217189-4fb03901-12b8-4b38-9d5a-355c2760adcf.png)

Card Info
---
- [x] Container max-width was removed in ab6a68ec4913e2205b25ab1aaffbb4e9c32efc5f, leading to excessive padding in wide windows.
- [x] Almost no margin on the left, making it cumbersome to read on crowded backgrounds. 
![grafik](https://user-images.githubusercontent.com/48286681/144220848-ca66d849-34d9-495c-a975-91213c957c06.png)
- [x] Differrently aligned columns lead to extremely uneven padding. I don't have any strong opinions on which column should have which alignment, but it doesn't look very pleasing with the current mix. Interval and Ease are hardly recognisable as separate columns without a closer look.
![grafik](https://user-images.githubusercontent.com/48286681/144220985-399ffd44-42a6-42ab-ad65-788ec47c6605.png)

Editor
---
- [ ] When removing a list tag without having text selected, field focus is lost. When I do it by shortcut, I also get several of these `JS error /_anki/js/editor.js:42866 Uncaught (in promise) IndexSizeError: Failed to execute 'getRangeAt' on 'Selection': 0 is not a valid index.`
- [x] Add-on button styles.

Congrats
---
- [x] Getting `JS error /_anki/pages/congrats.html:1 Uncaught SyntaxError: Identifier 'style' has already been declared` and I don't think it's supposed to look like this?<br> <img width=400 src=https://user-images.githubusercontent.com/48286681/144473914-7da89c2e-6e20-4032-87bf-9aef3fd74f57.png>

**Comment by kleinerpirat** [comment]
>  1-px top margin (Change notetype window on the right for comparison)

To keep it consistent, which margin would you prefer @dae @hgiesel?

Love that nitpick list! It was about time these issues get addressed :D

> What is the reason for the background box? Looks quite different than other dialogs.

I began wondering myself lately. It's there because I tried to make it look like the Qt interface (e.g. the Preferences screen) and also because I felt we needed a proper frame for the scrollable region of that window. We can get rid of the background color with no hard feelings. But I am in favor of keeping the border of that box, because otherwise it looks weird when cutoff dropdowns appear "out of nowhere" (no bottom margin for the whole scrollable area looks bad as well in my eyes).

> Name of target notetype is cut off at the bottom. ("g"s, "j"s, etc.)

Interesting. I can't think of a change in my PR regarding that dropdown and didn't notice it myself.

I'll get right to it 👍

**Comment by RumovZ** [comment]
> Interesting. I can't think of a change in my PR regarding that dropdown and didn't notice it myself.

Looking at my own screenshots, I realise that it's the same for the selector in the deck options. But curiously not for the deactivated selector in Change Notetype.

**Comment by kleinerpirat** [comment]
That's because they're different components. I used a deactivated `LabelButton` for the old notetype name, because `<select>` has an unwieldy min-width (not desirable for that UI element).

On my system, `<button>` gets the font `Noto Sans`, while `<select>` gets `system-ui, -apple-system, "Segoe UI", Roboto, "Helvetica Neue", Arial, "Noto Sans", "Liberation Sans", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji"`.
![image](https://user-images.githubusercontent.com/62722460/144287635-c5af6137-59f2-43bc-8778-3e447f93a2e8.png)

That's Bootstrap base styling. I'm wondering what's the most elegant solution for this.

**Comment by hgiesel** [comment]
> 1-px top margin (Change notetype window on the right for comparison)

I'll increase it to match the bottom margin. I don't think it has to match the ChangeNotetype one, as it's kind of different design (inside a sticky bar vs embedded on the page)

> Container max-width was removed in ab6a68e, leading to excessive padding in wide windows.

My reasoning here was:
1. If the user makes the window too big for its content, he probably has a reason for it. 2. The excessive inline margins also don't look too good.

> Almost no margin on the left, making it cumbersome to read on crowded backgrounds.

That should only happen if you make the window quit narrow anyway? I could increase the margin by a few pixels.

> regression of add-on button styles

@kleinerpirat Could you point out what you mean?

**Comment by RumovZ** [comment]
> If the user makes the window too big for its content, he probably has a reason for it. 2. The excessive inline margins also don't look too good.

I personally increase the window size because I don't want the card stats, especially the deck name, to wrap, which would lead to distracting vertical jumps when the card changes. Excessive whitespace on the right might not be the most elegant solution, but at least it doesn't exacerbate reading the window, whereas excessive cell padding makes it quite hard to keep ypur row while reading.

> That should only happen if you make the window quit narrow anyway? I could increase the margin by a few pixels.

As can be seen here, it takes a lot before padding on the left is increased, almost 800 px, while there is already an exuberance of cell padding.

<img src=https://user-images.githubusercontent.com/48286681/144303203-95ba585a-358d-48ca-99b3-10f1bb7b3fc6.png width=400>

**Comment by kleinerpirat** [comment]
> I'll increase it to match the bottom margin. I don't think it has to match the ChangeNotetype one, as it's kind of different design (inside a sticky bar vs embedded on the page)

I could also remove the border of the scroll area (what @RumovZ called "box") entirely and add that bottom border back to the StickyContainer of ChangeNotetype. It actually doesn't look as bad as I thought it would and then we'd have consistency across these sticky headers.

> regression of add-on button styles

Sure, sorry for not being clear @hgiesel. I noticed the buttons look less polished currently than they do on 2.1.49 for several reasons:
- they're larger
- they barely have vertical gutter
  - I'd say the perfect value is in-between the previous and current state.
- text doesn't adjust to night mode
- icon alignment is off (look at Closet occlusion button)
### 2.1.50
![image](https://user-images.githubusercontent.com/62722460/144312082-c09941e2-2797-4fb8-b097-98dc18492834.png)

### 2.1.49 (same window size)
![image](https://user-images.githubusercontent.com/62722460/144312199-85f5e450-3fa0-4f3b-a611-e5d0526221be.png)

I thought already know about this due to [this forum post](https://forums.ankiweb.net/t/new-toolkit-and-packaging-test-windows/14081/5?u=kleinerpirat), but you meant something different there.

**Comment by dae** [comment]
> Differrently aligned columns lead to extremely uneven padding. I don't have any strong opinions on which column should have which alignment, but it doesn't look very pleasing with the current mix. 

Sorry, I'd meant to reply to this earlier. The current behaviour was introduced in fd013f68d2de8cfc58a6f4ecce4519e6c3acd260. My thinking behind the alignment change is that it makes it a bit easier to see scale changes across a single unit (eg 1 day, 10 days, 100 days) more easily, and numbers in spreadsheets tend to be right aligned. The fact that the unit can change makes it quite a bit less useful, but it seemed to be the least bad option compared to centered or left-aligned text. So my focus was on reading the individual column, rather than than spacing of the different columns. Maybe we could solve the latter a different way, like adjusting the order they're shown in? I don't have strong feelings here, and am open to alternative options.

**Comment by dae** [comment]
Style issue is fixed. 

@RumovZ what did you mean by "list tag"? Is it still an issue?

Are there any other things we need to address here?

**Comment by RumovZ** [comment]
I mean HTML tags, so `ol` and `ul`. It seems to have improved: I can't reproduce the issue without using shortcuts, and I don't get JS errors either anymore. To reproduce the still existing issue, press <kbd>Ctrl+,</kbd> twice while the cursor is inside an editor field with no current selection. The cursor will disappear while the field is still highlighted, and you have to restore it by clicking or tabbing.

**Comment by hgiesel** [comment]
@RumovZ I remember it being the same behavior in 2.1.49. This seems to be the built-in behavior of `document.execCommand`. Fixing it will require to implement the behavior from scratch, which is certainly not impossible (Summernote did it), but will be a bigger endeavour, just like rewriting the surrounding logic of the bold,italic,etc. buttons. I'll certainly get there :)

**Comment by RumovZ** [comment]
Ah, okay. Would have been nice if it was an easy fix, but not a big deal. 
I misremembered above: What I originally meant by triggering the issue without using shortcuts was clicking the buttons, not pressing backspace. Clicking the buttons is still causing the issue, just like when using the new shortcuts.

**Comment by dae** [comment]
Ok, with that last remaining issue going to take some time, let's call this issue fixed :-) Thanks everyone for these fixes.
