### ISSUE TITLE
customize 'blank' replacement in TTS

### ISSUE THREAD

**Issue by dae** [ankitects/anki#1537]
Following on from https://github.com/ankitects/anki/issues/1171

Some users don't like the `blank`, and want to be able to turn it off. It would be nice if we could solve this in a way that doesn't require extra DB lookups on each card render.

One option would be to revert to the old behaviour, then provide a more general solution with a new filter, eg:

```
{{tts en_US:replace [...]=>blank:Field}}
```

Or it could be a specific argument to tts:

```
{{tts en_US blank_cloze=blank:Field}}
```

Another option would be to stuff the option into the notetype (which is cached). We'd need to decide on whether it's a simple boolean, a string of the desired replacement text, or an arbitrary list of replacements.

Thoughts?

**Comment by RumovZ** [comment]
> {{tts en_US:replace [...]=>blank:Field}}

I wonder if there are any use cases for this outside tts. I could imagine some if regex were supported, but we probably don't want to compile arbitrary regex whenever rendering a card, do we?

I think a notetype option would only work for the simplest solution where the user can decide whether to pronounce the blank or not. If a replacement is possible, it should depend on context, because the biggest problem I see with the current solution is that the tts voice and the blank localisation aren't in the same language. But there may be different languages on a notetype (on different or even the same cards), and a simple replacement could only fix one.

**Comment by dae** [comment]
Thanks, good points. Maybe we're best off focusing on the cloze case, and only in the tts tag.  I guess we have a few options:

- a boolean on/off for the previous/current behaviour
- defaulting to on, with the ability to define a different replacement (eg `{{tts en_US blank_cloze=:Field}}` - it would depend on us allowing an empty value for that argument)
- defaulting to off, but as above

Based on the number of people who have complained about blank vs previously requested the change I'm guessing 'blank' might be the better default, but it is only a guess, and I could be wrong.

**Comment by RumovZ** [comment]
Defaulting to on might also be better in terms of disoverability. Unlike silence, "blank" demonstrates to the user that there's a deliberate design choice and it's customisable, at least by devs.

**Comment by dae** [comment]
Yep, good point. 

Currently our tts filter doesn't attempt to parse the arguments, and just passes them on verbatim to the [anki:tts] tag. So once a decision is reached on #1507, support in {{tts}} tags should be basically "free", aside from needing to avoid a colon.

**Comment by dae** [comment]
Ok, so once we have a parser going, how about blank_cloze="some text", with the default, if not provided, being the i18n'd 'blank'? Our parser could either allow empty values (`blank_cloze=`), or if we don't want to do that, the user could presumably use `blank_cloze=...` instead?

**Comment by RumovZ** [comment]
An alternative would be `blank_cloze=""`, which wouldn't require any special casing. However, I don't see a problem with `blank_cloze=` either.

**Comment by dae** [comment]
Either works for me :-)
