### ISSUE TITLE
The inconsistency of the hard button delay with the scheduler 2.1 specifications (learning cards)

### ISSUE THREAD

**Issue by ksofiyuk** [ankitects/anki#1555]
According to the documentation, when you press the hard button you expect to get the average of the first and second steps on the first step and the repetition of the current step on the next steps:

> Hard repeats the current step after the first step, and is the average of Again and Good on the first step. [Anki Manual](https://docs.ankiweb.net/studying.html#learningrelearning-cards)

> Hard will repeat the current learning step (except on the first step, where it is the average of first and second steps). [Anki FAQ](https://faqs.ankiweb.net/hard-good-interval-longer-than-good-easy.html)

However, when I set the following learning steps for my deck "2h 2h 1d 3d 6d", I always get the average of the current and the next steps, for example, 13 hours on step 2 instead of 2 hours, and 2 days instead of 1 day on step 3. This behavior occurs both for Anki 2.1.49 and AnkiDroid 2.15.6.

I checked the code of the scheduler and found out that it always averages the current and the next steps (line 654) which contradicts the specification of the scheduler:

https://github.com/ankitects/anki/blob/eb839f0ba29192c3fa41f4dd0c71712a3b358082/pylib/anki/scheduler/v2.py#L1042-L1050

https://github.com/ankitects/anki/blob/eb839f0ba29192c3fa41f4dd0c71712a3b358082/pylib/anki/scheduler/v2.py#L647-L655

**Comment by RumovZ** [comment]
Note that this is the v2 scheduler, but the manual should describe the actively developed v3 scheduler if not stated otherwise. Here is the counterpart for v3:

https://github.com/ankitects/anki/blob/eb839f0ba29192c3fa41f4dd0c71712a3b358082/rslib/src/scheduler/states/steps.rs#L41-L62

As you can see, it was supposed to be a direct port of the v2 code, even though the logic is flawed. I expect by now, @dae doesn't mind a quick PR to fix this in v3 (after #1548 to avoid conflicts), but I wonder what the intended behaviour for v2 is.

**Comment by ksofiyuk** [comment]
I guess the current documentation describes exactly the behavior of the hard button in the 2.1 scheduler as it was there even more than a year ago (https://web.archive.org/web/20200929200130/https://faqs.ankiweb.net/the-anki-2.1-scheduler.html) - before starting the development of the v3 scheduler.

**Comment by dae** [comment]
Looking through the code and documentation history:

- the code has used the same approach since it was first introduced - it "repeats" the current step by not decrementing the remaining steps count, but it uses a delay that's the average of previous+current step
- the documentation originally just said "repeats the current step" https://web.archive.org/web/20181204210033/https://anki.tenderapp.com/kb/anki-ecosystem/experiment-scheduling-changes-in-anki-21.
- the code was [later adjusted](https://github.com/ankitects/anki/commit/730d444164075b9377bef7b7c65003e0a14e7005) to better handle the case of a single learning step, and I imagine the documentation error slipped in when that change was later summarised for the release notes.

IIRC, the averaging was done to ensure each button presents a different number. If we repeated the prescribed delay instead, I think we'd end up in the same situation that the above commit was trying to prevent, where again and hard give the same number after failing a card.

**Comment by RumovZ** [comment]
> IIRC, the averaging was done to ensure each button presents a different number.

That is reasonable, but only if the hard/current step is the same as the again/first step. To me it looks like the implementation fell short of the intent expressed in the manual and ended up only handling a special case.

**Comment by dae** [comment]
Well, with the default 2 steps, the "special case" is about 50% of the time :-) But as long as we keep the delays on the buttons distinct (since users tend to assume something's broken when the same delay gets repeated on multiple buttons), I don't have any objections to an alternative approach - did you have something in mind?

**Comment by RumovZ** [comment]
> Well, with the default 2 steps, the "special case" is about 50% of the time :-) 

True, and in the other 50% it works out as well, because it's the last step. This is only relevant for 3 steps or more.

Current bahviour:
1. First step: Hard is average of first/current and second/next step.
2. Last step: Hard is current step.
3. All the steps in between: Hard is average of current and next step.

I propose to implement the behaviour described in the manual: Keep 1, but make 3 behave like 2.
