### ISSUE TITLE
memory leak in browse screen

### ISSUE THREAD

**Issue by dae** [ankitects/anki#1589]
browse screen open/close leaks memory: https://forums.ankiweb.net/t/opening-and-closing-browse-permanently-increases-memory-usage/16655

**Comment by dae** [comment]
Thanks, I accidentally cut off the last digit.

**Comment by dae** [comment]
Looks like the sidebar might be the main culprit:

```
>>> import tracemalloc
... aqt.snapshot1 = tracemalloc.take_snapshot()
<no output>
>>> aqt.snapshot2 = tracemalloc.take_snapshot()
... 
... top_stats = aqt.snapshot2.compare_to(aqt.snapshot1, 'lineno')
... 
... print("[ Top 10 differences ]")
... for stat in top_stats[:10]:
...     print(stat)
[ Top 10 differences ]
qt/aqt/browser/sidebar/item.py:71: size=121 KiB (+72.7 KiB), count=1069 (+642), average=116 B
qt/aqt/browser/sidebar/tree.py:785: size=36.6 KiB (+21.9 KiB), count=390 (+234), average=96 B
qt/aqt/browser/sidebar/item.py:79: size=29.3 KiB (+17.6 KiB), count=535 (+321), average=56 B
qt/aqt/browser/sidebar/tree.py:798: size=18.9 KiB (+11.5 KiB), count=199 (+120), average=97 B
qt/aqt/browser/sidebar/tree.py:794: size=18.3 KiB (+11.0 KiB), count=195 (+117), average=96 B
qt/aqt/main.py:1594: size=22.5 KiB (+10.7 KiB), count=71 (+27), average=325 B
<string>:3: size=16.1 KiB (+9048 B), count=318 (+174), average=52 B
pylib/anki/collection.py:625: size=14.5 KiB (+8928 B), count=155 (+93), average=96 B
qt/aqt/browser/sidebar/item.py:73: size=14.1 KiB (+8634 B), count=180 (+108), average=80 B
qt/aqt/__init__.py:632: size=30.8 KiB (+8336 B), count=211 (+1), average=150 B
```

**Comment by RumovZ** [comment]
I spent a long time looking for leaks in the browser and sidebar, and actually found a couple. However, they didn't fix the noticeable memory leak. I then made a curious discovery that isn't limited to the browser.
To reproduce, execute the following:

```
import gc
import weakref

d = aqt.dialogs.open("FilteredDeckConfigDialog", mw)
aqt.r = weakref.ref(d)
pp(gc.get_referrers(aqt.r()))
```

You'll see some referrers, nothing unexpected. Close the dialog and give it a sec for the scheduled garbage collection to take place. Then execute:

```
import gc

if aqt.r():
    pp(gc.get_referrers(aqt.r()))
```
You'll see that the dialog still exists and is kept alive by some opaque cell. However, something like `aqt.r().close()` will fail with `RuntimeError: wrapped C/C++ object of type FilteredDeckConfigDialog has been deleted`. So the Qt object has been deleted, but our Python instance has not. It's still accessible with all its fields. In the case of the browser, that's a lot, including the sidebar, table and editor.
I chose `FilteredDeckConfigDialog` because it's simpler than the browser, but still causes the same issue. In contrast, the about screen does not. Maybe because it's not overriding QDialog's constructor.

This all seemed very strange to me, so I wanted to check with you first. What do you think? Did I make a mistake somewhere or does this look like a major concern? And if so, do you have any suggestions how to proceed?

**Comment by dae** [comment]
(see #1672 for further discussion)
