### ISSUE TITLE
v3 Scheduler: Deck limit enforcement of nested children

### ISSUE THREAD

**Issue by giulianorasper** [ankitects/anki#1654]
According to the manual, "each child deck's limit is also enforced".
However, this is not the case for nested decks with a depth greater than one.

Assume we have following nesting:
`A (9999) -> B (100) -> C (9999)`
with A being the topmost parent and new cards limits in parentheses.

If studying is started by clicking on the A deck, the children restrictions should be enforced, i.e.:

1.  there will be at most 100 new cards from deck B
2. there will be at most 100 new cards from deck C
3. there will be at most 100 new cards from deck B and C combined

However, it seems like the restriction of B is not applied to C in this case, i.e. 9999 new cards from deck C could be studied.

**Comment by dae** [comment]
The behaviour is documented on the v3 scheduler page, but work is currently underway to bring this behaviour more in line with previous scheduler versions.

**Comment by porcoesphino** [comment]
Any updates on when "more inline" might land?

Or a reference to downgrading the scheduler? It seemed like I had to upgrade but it's clearly a bit rough and this is enough of a blocker I'm happy to rely on the iphone backups until this is improved

**Comment by porcoesphino** [comment]
Wait, why is this closed? The behaviour is the same as when the issue was opened and there was a note of aligning behaviour so future actions

**Comment by dae** [comment]
I suspect you and the OP are talking about different things. Previously, when you clicked on A, the limits from B were not applied to C. That is no longer the case. I suspect you are taking issue with the fact that A's limits are not applied when you click on B. I'm afraid that is unlikely to change, as the new behavior allows people to review subdecks even if their parent deck's limits have been reached.

Please note that support for the v2 scheduler is likely to be dropped from the mobile clients quite soon, so if you feel you can't live without it, I'd recommend disabling automatic app updates.

**Comment by porcoesphino** [comment]
Ahhh... thanks for taking the time here. That seems odd to me, because custom sessions worked for that didn't they? Let me flesh out the use case and why its a problem to me. Maybe it's worth a new issue, or you have a solution and someone else reads this.

So I have a single deck with a relatively large number of sub-decks.

The single deck had a new card limit that I use to make sure that my reviews stay within a reasonable limit as time progresses. This seems important to all people, is emphasised in the manual, and I'm doubting we have different viewpoints here. I then have sub-decks with different topics each with different new counts (some material only makes sense to learn at a given rate). But it's still important here that I don't go over my parent new card limit, or things escalate into a review nightmare. I'm pretty sure you agree with this too.

Since I have a multiple topics I'd love to learn, I set them all to reasonable individual new card limits and then have a parent deck that enforces a review limit that won't become overwhelming. If I review from the parent the new cards are added from decks at the top (i think) so when I woke up motivated to learn a few topics I'd just just click the decks I wanted to learn about and eventually decide to review things together. This style I guessed was common but it can't be because now it's far too easy to pile up reviews and end up with disgruntled users that won't touch the app again. I'm guessing there is a common pattern people use instead that you can point me to?

I'd sometimes use this layout to help with review motivation too. The parent deck sometimes is very manageable, and sometimes has a larger number of reviews (or framed another way, sometimes I have lots of energy to complete all the reviews and other times I have less). I would manage my motivation by reviewing in the sub-decks, and at some point finishing in the parent deck. With the recent changes, if I wanted to do this multiple times before finishing with a review of the parent deck, it's very easy to accidentally accumulate new cards. This just makes the reviewing accumulation worse, and again, I'd expect tired users that use the app less so people must be doing something different here too. I tried to solve this with custom study to force the subdeck to have no new cards temporarily but this doesn't seem to work. I think I'm expected to drop the new cards to zero then increase the number again at a later date. Are people just double something really differently here?

One the specific day this happened I was playing catch up and wanted to do my reviews by sub-deck to manage motivation and I wanted to temporarily make the parent decks new cards zero to manage the work load until I had things under control again. I'm not sure how I'd do this now besides clicking through every subdeck and setting them to have zero new cards and toggling back and forth here isn't going to be fun.

Maybe people are just more motivated than me here but it seems like the current system can quite easily have new cards accidentally overwhelming the user and I think that has issues for users motivation and long term use.

I know this is too late now, but for the problem you described this as fixing, what doesn't a large review count on the parent deck suffice? Thats what I use. If there impressively hitting integer maxes or something then an unlimited seems like an option that wouldn't have removed those flows.

Anyway, these changes are never going to please anyone but thanks for taking the time and sorry this wasn't better edited. Your work does deserve more than the late night reply from a phone I'm giving you

**Comment by dae** [comment]
The current approach allows users to have a global limit on their top deck, but also see how many cards are due in their child decks - many users found it confusing when they knew they had a deck with cards in it, and a high enough daily limit on it, but still the deck showed 0. It also enables a user with a global top-level limit to study up to their daily limit, and then click on one of the subdecks to study more if they wish - which is easier than creating a custom study deck, especially as the cards remaining are immediately visible.

If your child decks share a preset, you could just edit that preset and use the option that allows you to alter the daily limits for a single day - the next day, they'd reset to what they were before.
