### ISSUE TITLE
Mathjax get deleted even when cursor is on it's left

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankitects/anki#1726]
Tested on d100f7a2c8681b2d4dd1bf03797ef8fb3157358b

Reproduction:
* In a field, enter some mathjax content
* Move the cursor immediately to the left of the mathjax content (you can enter mathjax and use the left arrow. Or you can click on the left of mathjax and press the right arrow once. You arrive at a position that is not reachable by clicking)
* press backspace (the touch to delete what is on the left)

Expected result:
* Nothing occurs since mathjax is on the left part of the field. In particular mathjax remains

Actual result:
* Mathjax content is deleted. Element that appears on the left of the cursor remains (worse: you can't just use ctrl-z to cancel)

The same thing occur with cursor on the right and pressing delete.

This is a minimal example of the bug. It comes from real issue I had with editing the notes, but I simplified it as much as I could to explain it. I lost quite a lot of equations due to it until I finally understood what was occurring. For context, what occurred is that I had fields `Let ($)n\in\mathbb N(/$)` and I wanted to remove "Let". So I double clicked on "let", pressed back key, then moved to the right using the keyboard to check whether a space remained; since I was still on the left of mathjax, I concluded that a space remained, pressed "backspace" and here it is, I lost my mathjax

**Comment by roxgib** [comment]
To clarify, is 'Let' part of the MathJax or outside it?

Is it possible that what was happening was:
- Paste `Let ($)n\in\mathbb N(/$)` into the field
- Select the equation and make into MathJax using Ctrl-M, M
- Double click 'Let' and press backspace (which also deletes the space in front of 'Let', even if it isn't selected)
- Press Right, which (because the space was deleted in the previous step) opens the MathJax editor and selects the entire equation
- Press backspace, which deletes the equation since it's now selected

This occurred to me when I followed your steps exactly, but looked to be expected behaviour as it was caused by opening the editor. Perhaps the MathJax editor is opening but not displaying for you for some reason? 

FYI it seems that MathJax supports Ctrl-Z while the editor is open, but confirming it prevents any further undos, but you can in fact Ctrl-Z it if you open the HTML editor, put the cursor in there, and then press Ctrl-Z. I might open a separate issue about that.

**Comment by Arthur-Milchior** [comment]
"Let" is outside of mathjax. Sorry, for some reason I thought mathjax was done with ($). After rechecking, I meant 
`Let \(n\in\mathbb N\)`
Also,  when this text is in the field, I don't have to pres Ctrl+M, M to transform it into anki's mathjax. I just need to leave the field.

After trying to reproduce more, there is a stranger behavior. Sometime, after pressing the right key, I enter the mathjax window. Sometime I remain outside of the mathjax window and is in this strange position, where the cursor appears on the left of mathjax, but pressing "back key" still delete it. 
The two behaviors can occurs with the same field, without making a single change, and I don't understand it

**Comment by dae** [comment]
@hgiesel would this be difficult to fix for 2.1.50?
