### ISSUE TITLE
Cards with inexisting ord appears as deleted

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankitects/anki#1729]
How to reproduce:
* manually change the ord of a card of a normal note type in the db. Make it big enough that it does not correspond to a card type ord
* Open the browser and search for the note with this text

Expected result:
* really not clear honestly. Probably an invitation to check the database

Actual result:
* the card appear as deleted. While it still exists actually. 

This is a trouble mainly because it mean that I can't access the note content (fields, tags) so I can't even check which note it is. Also it means I can't just  use the advanced browser feature that allow to edit card properties from the browser (not that it's a feature that I regularly use. But it would allow for manual correction)

**Comment by RumovZ** [comment]
That should just require mapping this error to something else:

https://github.com/ankitects/anki/blob/704fb918c3c36cd3775b14fde172100d5976de1a/rslib/src/browser_table.rs#L396-L398

**Comment by RumovZ** [comment]
Makes sense. I don't think selection is currently disabled for broken rows, so that would need to be changed as well. Add-ons like Advanced Browser could simply use the `browser_did_fetch_row` hook to reenable rows.
Not sure if Check Database should be universally recommended in the described use case, as it would delete cards with broken ordinals and create new ones, if I'm not mistaken.

Showing the error's localisation is also not particularly helpful currently, because that's only a vague NotFound error. Maybe this error should at least indicate what kind of object wasn't found? To keep it ergonomic, or make it even more ergonomic, we could define a trait:

```rs
trait OkOrNotFoundErr {
    type Inner;
    fn ok_or_not_found_err(self) -> Result<Self::Inner>;
}

impl OkOrNotFoundErr for Option<Deck> {
    type Inner = Deck;
    fn ok_or_not_found_err(self) -> Result<Self::Inner> {
        self.ok_or(AnkiError::NotFound(AnkiType::Deck))
    }
}
```

(Real implementation would probably be a lot more generic.)

**Comment by dae** [comment]
At one point it might be worth sitting down and having a good think about our current error handling to see if we could be doing anything better. Showing the type of item would be a step in the right direction, but often it would be even more helpful to provide the specific ID in question, and it would be nice to be able to attach arbitrary context to our errors.

In the short term though, perhaps we could just map the one or two get_card/get_note calls in the browse_table code to a separate error which we map to deleted as a quick fix? I'm not sure we can do much better than recommend a DB check, as without one it would require the user to manually fix their collection.
