### ISSUE TITLE
Unify exposed MathJax add-ons

### ISSUE THREAD

**Issue by dae** [ankitects/anki#1773]
We appear to be exposing mathtools in the editor but not reviewer; we should be consistent.

https://forums.ankiweb.net/t/anki-2-1-50-beta-6-release-candidate/18181/99

**Comment by danishprakash** [comment]
Hey @dae, mind If I take a shot at this? If it's not on priority, that is.

**Comment by hgiesel** [comment]
@danishprakash 
Some background:
The mathjax setup for the reviewer is in [mathjax.js](https://github.com/ankitects/anki/blob/main/qt/aqt/data/web/js/mathjax.js).
Mathjax has a somewhat weird method to configure it by first defining the configuration in a global variable (window.Mathjax), and then loading Mathjax, which will then read from this global variable, and replace it with an Mathjax instance.

It seems for the editor we use some kind of default configuration, because we don't configure it this way. This default configuration seems to include much more functionality, than what we configure in [mathjax.js](https://github.com/ankitects/anki/blob/main/qt/aqt/data/web/js/mathjax.js).

In the editor, we import Mathjax directly, so we can parse on demand in [ts/editable/mathjax.ts](https://github.com/ankitects/anki/blob/main/ts/editable/mathjax.ts).

I *think* the solution is either to find a way to include a config in the editor, as we do in the reviewer (we'd need to configure `window.Mathjax` before loading Mathjax), OR find a way to provide a configuration for the `globalThis.MathJax.tex2svg(input)` call in `ts/editable/mathjax.ts` (also ideally import it from somewhere, and not just it as a global), OR simply add all the extensions that are loaded in the editor to the reviewer (least desirable, as we'll have a weird dependence here: Our mathjax.ts config needs to match the Mathjax defaults).

**Comment by dae** [comment]
Please go ahead - it's not super urgent. @hgiesel's reply is a good summary, and I agree it would be preferable if we could get the editor to match the reviewer behavior here (and preferably with a shared config file, instead of manual copy+paste). A case could be made for including mathtools by default in the future, but that's a separate issue that we can consider independently of this one.

**Comment by dae** [comment]
It seems we haven't fully fixed this yet: https://forums.ankiweb.net/t/degrees-symbol-not-working-on-front-of-card/21281

**Comment by dae** [comment]
https://forums.ankiweb.net/t/report-a-bug-for-2-1-45/22621

**Comment by dae** [comment]
https://forums.ankiweb.net/t/degree-upgreek-gensymb-latex-packages-not-working-in-anki-study-mode-only-in-preview/26990
