### ISSUE TITLE
image changes size when pressing enter

### ISSUE THREAD

**Issue by dae** [ankitects/anki#1804]
https://forums.ankiweb.net/t/2-1-50-images-in-editor-changing-size-seemingly-randomly/19096

**Comment by hgiesel** [comment]
What makes this so difficult is that the "constrained size" vs "full size" state is entirely an editing phenomenon of visual editor. The underlying HTML does not change.
Now when the HTML editor pushes a change, and the visual editor updates according to it, it forgets everything about it. It couldn't tell whether the pictures are still the same, or switched places, because the user can have the same picture in a field twice, at which point, the editor can only distinguish between both pictures by their children path from the root. (basically `anki-editable.children[n].children[m]...` etc.)

Maybe I should revamp this approach, because those two things cannot be harmonized (content of visual editor can be updated by HTML editor, **and** visual editor keeps fullsize/constrained info completely private).

What would you say, if we made the fullsize/constrained state part of the content that is saved to disk, e.g. like this
```html
<img src="myimage" data-anki-fullsize="true" />
// or
<img src="myimage" data-anki-fullsize="false" />
```

This would solve a lot of this random/unexpected resizing, and it would mean that a person does not want a certain image's size to be constrained, they only would have to set it once. WDYT?

**Comment by dae** [comment]
Thanks for explaining the issue, that was helpful. 

> because the user can have the same picture in a field twice

Theoretically - but I wonder how much that actually happens in practice? I can't think of a reason off the top of my head why a user would place the same image into a field multiple times. If they are unlikely to do that, maybe it doesn't matter so much if all instances of the image get resized at the same time?

> What would you say, if we made the fullsize/constrained state part of the content that is saved to disk

If we decide that we want the zoomed/unzoomed state to persist across editor sessions and Anki restarts, then saving it into the HTML seems like the best option (though it would be nice if we omit the data attribute in the common case, and only write it in the toggled case). 

If however we want to automatically forget the zoom state each time we switch notes or close the editor, then having the state persisted to disk may make our life more complicated than using in-memory state instead.

I have no strong feelings here - which approach do you think makes more sense?

**Comment by hgiesel** [comment]
I have in mind the use case of the person on the forum using images of PDFs, or generally images with a lot of text on it. This makes me think, that it would make more sense if the state persisted during editor reloads, etc.

**Comment by dae** [comment]
Yeah, I can imagine some users would like it that way. I can think of some possible issues with a data- approach:

- it requires writing/syncing note changes even if the user was just "browsing" the notes/images
- if users in the future request that the zoom is automatically reset, that might be more complicated to implement if we're persisting state to disk

Whether they'll turn out to be issues in practice though, I don't know. And there are downsides to the in-memory approach too. Happy to go with data- if you think it's the better option. :-)
