### ISSUE TITLE
support cloze button while mathjax editor active?

### ISSUE THREAD

**Issue by dae** [ankitects/anki#1822]
How difficult would this be? I'm assuming https://forums.ankiweb.net/t/can-live-preview-of-mathjax-be-tunred-off-in-the-card-editor/19414/5 was talking about the MathJax macros and not the cloze button. :-)

**Comment by hgiesel** [comment]
Maybe this is a good time to talk a little bit about toolbars in the editor in general.

When you're in the Mathjax editor, the top toolbar is not greyed out, so it _seems_ active, even though is not.
If we wanted to enable the cloze button for the mathjax editor, we could:

1. Duplicate the cloze buttons in the Mathjax toolbar.
2. Gray-out the editor toolbar buttons when using Mathjax editor, except the cloze buttons, signifying that they are still usable.
3. This idea is a bit more far-reaching, and would become even more relevant, if we want to add toolbar buttons for the HTML editor:

[Here (only first picture is relevant + ignore positioning of the tag editor)](https://forums.ankiweb.net/t/position-of-the-tag-editor-in-2-1-50/16608/5?u=hengiesel) I've shown interest in moving the "Fields..." and "Cards..." buttons to another toolbar just above the current editor toolbar, so that the current editor toolbar only contains buttons which format the text somehow (and become inactive when no visual editor is selected).
This would mean that we can swap out the editor toolbar depending on the active editing input: the visual editor has its toolbar, the Mathjax editor gets its own, etc..

We could go for idea 1 or 2 now, and 3 later, once it becomes possible.

**Comment by dae** [comment]
3 sounds like it might be the best long term solution, though we'd need to wait for 2.1.55+ for that. How would you feel about doing either 1 or 2 for now, so that users have a workaround until we can make these bigger changes? 1 feels like it might be the simplest to implement/least likely to introduce regressions for now - does that sound good to you?
