### ISSUE TITLE
Consider providing a way to bypass review limits on new cards

### ISSUE THREAD

**Issue by dae** [ankitects/anki#1834]
Associated forum thread:

https://forums.ankiweb.net/t/v3-scheduler-new-cards-and-custom-study-behavior-question-requests/13870

Two possible approaches spring to mind:

- A "new cards ignore review limit" checkbox
- A "minimum new cards" option, that lets you specify the number of new cards that should be shown even if the review limit has been reached. Such a use case was anticipated when writing the v3 scheduler, and a `new_per_day_minimum` field already exists in the deck config.

The latter is more flexible - while a bit more complicated, it allows users to control how many new cards they want to be introducing when they're near or at the daily review limit.

Would need to figure out whether this should simply offset the review limit (eg if set to 5, the new limit is capped to min(reviews_remaining+5, new_remaining)), or whether it should override the the configured new limit. If the user specifies 0 new cards a day, but a minimum of 5, what should we do?

Other things that need consideration:

- How this will interact with extending the daily limits with custom study. Currently the user can extend their new card limit and find nothing changes, because their new cards are capped by the review limit already. Could the decisions we make here perhaps address that issue at the same time?
- How this will fit with the per-deck limits proposed on https://forums.ankiweb.net/t/set-daily-limits-separately-from-the-other-deck-options/17511

**Comment by Dolphyn5** [comment]
Some people (including myself) regard "new" and "review" as separate categories, so another way to resolve this issue would be to implement three separate daily limit settings:

- Maximum new cards per day
- Maximum review cards per day (not including new cards)
- Maximum total number of cards per day (new + review) OR (new + review + learning)

**Comment by dae** [comment]
I don't think burying is relevant to this issue, as the daily limits are adjusted based only on cards that weren't buried. I can't reproduce the issue in your latest forum reply; if I test with your AnkiWeb collection and disable burying of new cards in that deck's options, all 35 new cards are included.

Specifying a separate total instead of having an offset for new cards is a potential alternative solution, though I'm not sure that's the best approach - it's more disruptive as it alters the way reviews work as well, and it wouldn't be possible to tell Anki you want eg. a minimum of 5 new cards per day regardless of how many reviews are due.

**Comment by LordxRequiem** [comment]
Just wondering if any update on this issue. Very interested in a separate new/review pool as I'd like to better be able to "time" how long it will take me to get through the news in my deck, i.e. force Anki to always show me 10 reviews/day and only 50 reviews/day regardless of how many reviews are due. I have a very specific amount of time every day to do Anki and for this reason want to always have the same number of news/reviews due every day that I can determine.

**Comment by dae** [comment]
This will need to wait until 2.1.55 is out the door.

**Comment by FatAustralianStallion** [comment]
Sorry to keep bugging you about his issue but I was hoping to know what the timeline is looking like for separating the new/review pool. I have been using anki since about 2013 and I recently update to 2.1.57 as I really like the way V3 handles subdecks. I was not aware however how the new scheduler restricts the ability for users to determine how many new cards are seen each day. I am in a similar boat to LordxRequiem and have always preferred to tailor the daily new and review cards since I find different ratios work better for different topics (medicine/ language/ programming) and how close exams are.

**Comment by dae** [comment]
@RumovZ If it interests you, would you like to start investigating this?

**Comment by LordxRequiem** [comment]
> Sorry to keep bugging you about his issue but I was hoping to know what the timeline is looking like for separating the new/review pool. I have been using anki since about 2013 and I recently update to 2.1.57 as I really like the way V3 handles subdecks. I was not aware however how the new scheduler restricts the ability for users to determine how many new cards are seen each day. I am in a similar boat to LordxRequiem and have always preferred to tailor the daily new and review cards since I find different ratios work better for different topics (medicine/ language/ programming) and how close exams are.

100% agree with above, need finer control over the ratios of news/reviews (using for medical also). For my use case this new scheduler behavior has really limited how I use Anki. We really would appreciate your attention to this!

**Comment by RumovZ** [comment]
I feel like the "minimum new cards" option has become more intractable with the new deck-specific limits.
For one thing, would there be three spinners (preset, deck, today) for this new limit as well? That seems overkill, however, otherwise there's no intuitive precedence of one limit over the over. E.g. if I lowered the new limit of a certain deck for today only, would the minimum new limit of the preset still apply? Both answers yes and now have unsatisying consequences for certain use cases.

Then of course there's the additional complexity for the user. Even if we found a logical way to integrate this with the existing settings, it would probably still be very tough to grasp for the average user.

I would say these problems apply to a single checkbox, too, but to a much lesser extent. And it seems like this second option would be sufficient for everyone who posted here. Please correct me if I'm wrong.

However, maybe it would be clearer to flip the meaning of the checkbox: instead of "new cards ignore review limit", "limit new cards by review limit".

**Comment by LordxRequiem** [comment]
> I feel like the "minimum new cards" option has become more intractable with the new deck-specific limits. For one thing, would there be three spinners (preset, deck, today) for this new limit as well? That seems overkill, however, otherwise there's no intuitive precedence of one limit over the over. E.g. if I lowered the new limit of a certain deck for today only, would the minimum new limit of the preset still apply? Both answers yes and now have unsatisying consequences for certain use cases.
> 
> Then of course there's the additional complexity for the user. Even if we found a logical way to integrate this with the existing settings, it would probably still be very tough to grasp for the average user.
> 
> I would say these problems apply to a single checkbox, too, but to a much lesser extent. And it seems like this second option would be sufficient for everyone who posted here. Please correct me if I'm wrong.
> 
> However, maybe it would be clearer to flip the meaning of the checkbox: instead of "new cards ignore review limit", "limit new cards by review limit".

We are honestly just asking for Anki scheduler to go back to the way it was in V1 and V2. If I said I wanted 10 new/100 review per day, I always got 10 new/100 review and any leftovers just carried over into the next day. If sub decks all have limits of 20 new/200 reviews but the parent deck had limits of 10 new/100 reviews, I'd still only get 10 new/100 reviews just an ideally random mixture of all of the available news/reviews from the subdecks (depending of course on how fetch behavior was set but I always set it to be random between all subdecks). 

Is there really no way to just change it back to how it used to be? Back in ~2019 Anki did everything I wanted it to for me and I never would have updated the scheduler if I wasn't forced to. My girlfriend is still using a version from ~2019 and is only updating because the old software literally won't run.

**Comment by FatAustralianStallion** [comment]
> I feel like the "minimum new cards" option has become more intractable with the new deck-specific limits. For one thing, would there be three spinners (preset, deck, today) for this new limit as well? That seems overkill, however, otherwise there's no intuitive precedence of one limit over the over. E.g. if I lowered the new limit of a certain deck for today only, would the minimum new limit of the preset still apply? Both answers yes and now have unsatisying consequences for certain use cases.
> 
> Then of course there's the additional complexity for the user. Even if we found a logical way to integrate this with the existing settings, it would probably still be very tough to grasp for the average user.
> 
> I would say these problems apply to a single checkbox, too, but to a much lesser extent. And it seems like this second option would be sufficient for everyone who posted here. Please correct me if I'm wrong.
> 
> However, maybe it would be clearer to flip the meaning of the checkbox: instead of "new cards ignore review limit", "limit new cards by review limit".

Thank you RumorZ for taking the time to consider how this would be implemented it is much appreciated.  As LordxReqquirium said we were simply hoping to have an option/setting that allows V3 users to modify the number of new cards in the same manner as the V1 and V2 scheduler. I can understand why beginners might find the V3 scheduler easier to grasp but I don’t feel that warrants removing the ability for all more advanced users to control the ratio of new cards. I have reverted back to the old scheduler however I feel like I am missing out on a lot since I like the appearance and subdeck functions of the newer versions.

**Comment by dae** [comment]
@RumovZ at least with this small sample size, we seem to have confirmation that a toggle will be sufficient. Have I understood you correctly that you're suggesting the boolean be placed in the preset, and apply regardless of which tab the user has selected? That seems reasonable to me. You could even rename and repurpose the existing option I mentioned, as a) it should be 0, and b) converting from uint32 to bool is valid in protobuf, though it would mean the boolean would need to enforce the review limit when false.

**Comment by LordxRequiem** [comment]
> @RumovZ at least with this small sample size, we seem to have confirmation that a toggle will be sufficient. Have I understood you correctly that you're suggesting the boolean be placed in the preset, and apply regardless of which tab the user has selected? That seems reasonable to me. You could even rename and repurpose the existing option I mentioned, as a) it should be 0, and b) converting from uint32 to bool is valid in protobuf, though it would mean the boolean would need to enforce the review limit when false.

I think an unforeseen consequence of the V3 scheduler is just how penalized the user is for skipping days. In a perfect world yes I would love to study 100% of days and have an ideal review load but if I miss one day I am snowed with reviews and don't see any new cards for days on end. Practically speaking when studying for exams or other events, it's more beneficial to be able to consistently work through news and see everything at a steady rate at the sacrifice of completely optimized review load/interval.

**Comment by LordxRequiem** [comment]
> @RumovZ at least with this small sample size, we seem to have confirmation that a toggle will be sufficient. Have I understood you correctly that you're suggesting the boolean be placed in the preset, and apply regardless of which tab the user has selected? That seems reasonable to me. You could even rename and repurpose the existing option I mentioned, as a) it should be 0, and b) converting from uint32 to bool is valid in protobuf, though it would mean the boolean would need to enforce the review limit when false.

I think the feature would ideally randomly shuffle/equally weight all new cards available in all subdecks. This was previously accomplished by the Hoochie add-on pack, whereby a given day's new and review card pools comprised all available cards from all subdecks with equal weight such that no one subdeck was overrepresented (a problem with the older schedulers is that all news/reviews would disproportionately come from the first subdeck alphabetically, which was not the ideal/intended behavior).

**Comment by RumovZ** [comment]
Closed with #2417.

**Comment by LordxRequiem** [comment]
Thank you so much!! Can't wait to see it rolled out.
