### ISSUE TITLE
Provide opt-out of MathJax live preview

### ISSUE THREAD

**Issue by dae** [ankitects/anki#1942]
Until we can fix issues such as https://github.com/ankitects/anki/issues/1941 and things like [loading of macros](https://forums.ankiweb.net/t/can-live-preview-of-mathjax-be-tunred-off-in-the-card-editor/19414) and focus change issues, maybe we should provide an option to treat the MathJax code like we did previously.

**Comment by Arthur-Milchior** [comment]
If I can have a request, I'd appreciate if this can be a feature that is easy to change, from the field in the note editor, or something similar. Because while once in a while it may be useful, mathjax live is so useful almost all of the time that I would not want to have to deactivate it most of the time
