### ISSUE TITLE
Investigate shortcut issues in review screen in Qt 6.3/Windows/Linux

### ISSUE THREAD

**Issue by dae** [ankitects/anki#1952]
https://forums.ankiweb.net/t/bug-updated-to-2-1-54-and-e-to-edit-shortcut-no-longer-works/21109

**Comment by meehl** [comment]
I wanted to chime in and point out that this doesn't seem to be a Windows-specific problem. I started encountering the same issue with Qt6 on my Linux machine since 2.1.50 (Qt5 & Qt6 split) and it still persists in 2.1.54.

My issue is similar to the one described in this [comment](https://forums.ankiweb.net/t/bug-updated-to-2-1-54-and-e-to-edit-shortcut-no-longer-works/21109/5). I use type-in-the-answer cards which require me to input an answer in hangul(korean). After pressing Enter to confirm, the back card gets displayed but none of the hotkeys like 1/2/3/4 work. Pressing TAB once or clicking into the area at the bottom, where the ease level buttons are located, lets me use the hotkeys again.

versions and system info:
Anki Version ⁨2.1.54 (88e539aa)⁩
Python 3.10.5 Qt 6.3.1 PyQt 6.3.1
IME: fcitx5 5.0.18
WM: sway 1.7

**Comment by vintotal** [comment]
Do you think the following problem is related? On Windows, my keyboard shortcuts for language switching (Alt+Shit+1 to 6) make Anki crash. They work in other apps. To avoid the problem, I have to use Windows key + space.
    
Anki 2.1.54 (b6a7760c) Python 3.9.7 Qt 5.15.2 PyQt 5.15.5

**Comment by dae** [comment]
That's a long-standing Qt issue.
