### ISSUE TITLE
patch to bypass CORS for iframe-related cards

### ISSUE THREAD

**Issue by ericries** [ankitects/anki#2007]
I hope this is the right place to post this. I have been doing a lot of Anki using cards that are generated by third-party open source programs like chessli and anki-ogs. Some websites have a restrictive security policy that prevents their pages from being run inside an iframe, which AFAICT is the only way to get a full-screen web-based card. 

From the pyqt docs it looks like a relatively small change required to give the user the option to bypass this setting, which doesn't really provide any security for Anki (I understand why it's included in standard web browsers). If I produced a patch, would you accept it?

Alternatively, i could look into creating a way to specify a URL-based card that would direct pyqt to load that page as the top-level window. So http://example.com/id/{{itemId}} would work without an iframe

**Comment by dae** [comment]
What setting are you proposing to change? As far as I'm aware, the security policies are for the benefits of the sites themselves, not the site that is trying to embed them. Coincidentally, this popped up in my news feeds today: https://www.holovaty.com/writing/framebust-native-apps/.

Do those iframes work when viewing the cards on AnkiWeb? If not, then I would be reluctant to introduce a change to the desktop that didn't work on other platforms. If it just requires toggling a setting though, you can probably fairly easily do that in an add-on.

**Comment by ericries** [comment]
That's a funny coincidence. In this case, I think Anki is a legitimate browser unto itself. It's not trying to trick the user into not using the default browser. It's legitimately presenting the information (at the user's direction) that the user requested. 

I just tried both card types on AnkiWeb. The behavior is the same as on desktop - the site without restrictive CORS renders perfectly and the other cannot render. 

What do you think of the idea of allowing a card type that was simply a URL? that would avoid the problem of requiring an iframe 

In terms of the change I would make, it might be to use the existing "--disable-web-security" command line option that PyQt used to support (if it still does). Or I think it's possible to pass the relevant options through to QtWebEngine. If this is achievable via an add-on, I will be happy to do it that way, keeping the complexity out of the main app. Does this sound plausible as an approach?

**Comment by dae** [comment]
Disabling web security is not an option in the core code, as it would allow JavaScript to exfiltrate data from the local filesystem. If  you're happy to take that risk, you can set the QTWEBENGINE_CHROMIUM_FLAGS="--disable-web-security" env var before invoking Anki.

> What do you think of the idea of allowing a card type that was simply a URL? that would avoid the problem of requiring an iframe

It's not practical, as the review screen has its own logic in JS.

**Comment by ericries** [comment]
I just gave that a try, thanks for the pointer to QTWEBENGINE_CHROMIUM_FLAGS. Unfortunately, it didn't seem to work. I wonder if they've removed --disable-web-security from Qt, as I don't see it in the documentation anymore.

I guess the only solution will be to push the user outside Anki to the system default browser, as in the link you shared above. Unfortunately for the Anki use case, that's going to be quite a few extra clicks per-card, which will slow down reviews. I'll keep thinking if there's some way to solve the problem, perhaps as a plugin. Thanks again for your help (and for Anki itself, obvs!)

**Comment by dae** [comment]
I was able to access a local file when setting that flag, so it does seem to work - maybe it's just not a solution for your particular case. And add-on does sound like the best path forward.

And thank you for the kind words :-)

**Comment by khonkhortisan** [comment]
This is more complex than "How do I bypass `www.example.com refused to connect.`?"; the real question is "How do I incorporate scripted content into Anki?" Given a website, flip a coin for whether it fails to work in the false name of "security".

| puzzle | ❌refused to connect, or `mw.reviewer.web.setUrl() mw.moveToState("review")` | ❌linkless | ❌default language | ✔iframe | ✔imported |
| - | - | - | - | - | - |
| blackbox | | | | [gamegix](https://gamegix.com/blackbox/game?size=8&amp;balls=5) | | 
| ⌵checkers / draughts / ✳frisian | [⌵checkercruncher (setUrl)](https://www.checkercruncher.com/problems/755) | | | [⤫✳lidraughts](https://lidraughts.org/practice/rules-frisian/capturing-with-a-man/zn5H9gUj/TAjnuj7n) | |
| ♟chess/chinese/japanese/korean/laser/gungi | | [🐘wukong](https://maksimkorzh.github.io/wukong-xiangqi/apps/puzzle_solver/gui/puzzle_solver.html) [🐘xiangqi.com](https://play.xiangqi.com/puzzle/xLkw6L) | [☖playshogi](https://playshogi.com/#Problems:7:0:null)<br>[🇰🇷pychess](https://www.pychess.org/puzzle/janggi?janggi-piece=2) | [☖lishogi](https://lishogi.org/study/4XssSDlR?pieceSet=western)<br>[🔫laser-chess](https://laser-chess.com/)<br>[⚪gungi.io](https://gungi.io/) | [♟mate&advantage](https://ankiweb.net/shared/by-author/2023846080) [♟endgame](https://ankiweb.net/shared/info/689043906)<br>[🐘wukong](https://maksimkorzh.github.io/wukong-xiangqi/apps/puzzle_solver/gui/puzzle_solver.html) |
| 🔴connect four | | | | [🔴zeilberg](https://sites.math.rutgers.edu/~zeilberg/C4/ch1/P1.html) | [🔴zeilberg](https://sites.math.rutgers.edu/~zeilberg/C4/ch1/P1.html) |
| 📙dictionary spanish/sign | [🇪🇸dle](https://dle.rae.es/haber?m=form) [🇪🇸spanishdict](https://www.spanishdict.com/conjugate/haber)<br>[🧏‍♀️handspeak](https://www.handspeak.com/word/language/) [🧏‍♀️signingsavvy](https://www.signingsavvy.com/sign/sign+language/6097/1) [🧏‍♀️sldictionary](https://sldictionary.org/eng/dictionary/language) | [🧏‍♀️aslinteractive](https://aslinteractive.com/?s=language) [🧏‍♀️lifeprint](https://lifeprint.com/?search=language) [🧏‍♀️startasl](https://www.startasl.com/asl-dictionary/language) | | [🇪🇸verbix](https://www.verbix.com/webverbix/spanish/haber)<br>[🧏‍♀️signasl](https://www.signasl.org/sign/language) [🧏‍♀️signpuddle](http://www.signbank.org/signpuddle2.0/searchword.php?sTrm=language) [🧏‍♀️spreadthesign](https://www.spreadthesign.com/en.us/search/?q=language) | |
| fireboy & watergirl | [coolmath](https://www.coolmathgames.com/0-fireboy-and-water-girl-in-the-forest-temple) [crazy](https://www.crazygames.com/t/fireboy-and-watergirl) | [.site (⅚)](https://fireboyandwatergirl.site/forest-temple) [.org](https://fireboy-andwatergirl.org/) | | | |
| 🧬molecular folding/alignment | [eterna (🧬RNA)](https://eternagame.org/puzzles/11098074/play) | [foldit (🍗protein)](https://fold.it/) [phylo (🧬DNA)](https://phylo.cs.mcgill.ca/play.php) | | | |
| ⚫go | | | | [⚫online-go](https://online-go.com/puzzle/2625) | | |
| #hashi-o-kakero | | | | [#gamegix](https://gamegix.com/hashi-o-kakero/game?size=21&amp;diff=3) | | 
| ⊼logic gates | | [⊼nandgame](https://nandgame.com/) | | | |  
| ✖math | [khanacademy](https://www.khanacademy.org/math/ap-calculus-bc) | | | | |
| mensa | [mensa (setUrl)](https://www.us.mensa.org/play/games/games/play-four/?puzzle=01-24-25) | [mensa](https://www.us.mensa.org/play/games/games/play-four/?puzzle=01-24-25) | | | | 
| nonograms | | | | [gamegix](https://gamegix.com/nonograms/game?cols=10&amp;rows=5) | | 
| 🚗rush hour | | | | [🚗michaelfogleman](https://www.michaelfogleman.com/static/rush/) | | 
| 🌐user agent | [🌐whatmyuseragent](https://whatmyuseragent.com/) [🌐whatismybrowser](https://www.whatismybrowser.com/detect/what-is-my-user-agent/) | | | [🌐whatsmyua](https://www.whatsmyua.info/) | |
| ▶video | youtube live stream (h.264 not supported yet) | | | youtube video | | 
| languages | [🦉duolingo](https://www.duolingo.com/lesson/unit/1/level/2) | [🦉duolingo?](https://www.duolingo.com/lesson/unit/1/level/2) | | | | 
| 🪀 yo-yo | [🪀 yoyoexpert](https://yoyoexpert.com/pages/001-basic-yo-yo-types) | | | [🪀 yoyotricks](https://yoyotricks.com/yoyo-tricks/the-basic-throw/92/) | |

```html
<script>
if ("{{iframe url}}".includes("eternagame.org")) {
  if(!document.querySelector(".firefox"))) // use an x-frame-options addon instead
	window.location.href="{{iframe url}}"; // automatically open in external browser
}
</script>
```
```js
// ==UserScript==
// @name        close on focus loss
// @match       https://www.checkercruncher.com/problems/*
// @match       https://eternagame.org/puzzles/*/play
// @match       https://www.signingsavvy.com/sign/*
// ==/UserScript==

//discard second tab
document.addEventListener( 'visibilitychange' , function() {
    if (document.hidden) {
        console.log('bye');
        window.close();
    } else {
        console.log('well back');
    }
}, false );
```

- imported: the best state for a deck to be in. A self-contained .apkg, possibly with a .zip for media files or even loading online resources in any way that doesn't require an <iframe>. It is difficult to import scripted content such as board game puzzles, or a dictionary database that includes videos.
- iframe: Loads a website in Anki. Used because window.location.href can't be directly set to the website url. Unreliable because some websites don't want to be embedded and Anki normally respects that request.
- default language: The website will embed in an iframe, but the game pieces have chinese characters on them. There is no way to change the piece style using a ?querystring& in the url, so you need to pick one of
  - learn to read them 
  - change it every time the card loads 
  - somehow set a cookie inside of an iframe 
  - open it externally so you have the cookie 
  - find a replacement website
- linkless: Anki cannot directly open a specific puzzle. You may be able to manually select a puzzle through a menu. wukong has no querystring for the puzzle number, xiangqi.com only gives you the next puzzle link after you solve the current one so there's no list to import, phylo and foldit have non-html video game style menus that are partially navigable through macro software such as autohotkey.
- refused to connect: As far as I can tell, there is no rhyme nor reason for why a website is randomly placed in the iframe or refused to connect category. In this case, you can add javascript to the template to automatically open the url externally in your web browser, switch back to Anki to grade it, and add a violentmonkey script to automatically close its tab again when you're done

I personally have only been able to bypass `Refused to display 'https://www.example.com/' in a frame because it set 'X-Frame-Options' to 'sameorigin'.` with Firefox and Chrome addons, never in Anki itself.
firefox + https://addons.mozilla.org/en-US/firefox/addon/ignore-x-frame-options-header/ + ankiweb + iframe + checkercruncher or eterna or signingsavvy is a working combo, as long as I *don't* change window.location (because that would replace the ankiweb tab) nor use $jquery.

**Comment by khonkhortisan** [comment]
![Image](https://github.com/user-attachments/assets/a227a5cf-0e5e-4baa-88f6-12f818a781ac)

<img width="1200" height="675" alt="Image" src="https://github.com/user-attachments/assets/c835e69a-0556-46a8-978b-99295e217dd6" />
