### ISSUE TITLE
More template checks

### ISSUE THREAD

**Issue by RumovZ** [ankitects/anki#2024]
Based on recurring forum questions, here are two more ideas for template checks:

1. Multiple `type` filters
I believe there are add-ons supporting this. Is there a way to add a check for this without disrupting add-on users? Maybe we could mark the error as uncritical, so only a warning is shown, but the user may still save the template.
2. [Media references to fields](https://docs.ankiweb.net/templates/fields.html?highlight=img#field-references)
Is there any valid use case for this?

**Comment by kleinerpirat** [comment]
I'd find it nice if these template checks were default, but optional. They are a bit annoying if you know what you're doing, but just want to save field edits without having to worry about templates being compliant.

**Comment by dae** [comment]
The previous round of template checks were a mixed blessing - they've ensured people won't be able to create/distribute broken content going forward, but there was a lot of broken content already out there, and in some cases we changed minor display errors into a blocking issue that the user had to figure out, which also generated more support requests. I fear these two issues would be similar if we made them hard errors - we'd break things for people who use an add-on to support multiple fields, and there are some users who use latex tags in their templates to avoid entering them on each field, either because they're unaware that it's invisible to media checks, or because they don't care.

If we do address these two issues, I think it would be best done as a warning rather than an error - either via a pop-up shown before saving, or something like the the "cloze tags on normal notetype" tooltip - though implementing that here may be complicated if we want the logic on the backend, as we'd be sending the template across the wire each time the user types something, which is not very efficient.

**Comment by RumovZ** [comment]
Oh, I'd have thought they'd been a success, with only the poor communication after an export error causing some trouble, which is fixed by now. And of course, the benefits are less apparent, like the (hopefully) missing reports à la 'I'm seeing cards twice'.

An alternative to soft errors or a configuration like @kleinerpirat suggests would be a separate routine, comparable to _Check Database_. It wouldn't bother people while editing templates, but users would be asked to run it 'When problems occur'. I'd also run it when exporting, but users could be given the option to overrule a failed check.

**Comment by dae** [comment]
I feel like the best place to fix 1 would be in the card template editor - the fact that in the preview it shows multiple type boxes is what causes people to think that should work. Maybe we could just replace the 2nd+ box in that screen with a warning "only one field supported"?

For 2, maybe we could add a warning in Check Media, like is shown for subfolders?

**Comment by RumovZ** [comment]
Good idea.
If we iterate templates in Check Media, we might as well run the other checks, too, don't we? Do you want me to remove them from the Cards screen then?

**Comment by dae** [comment]
Which checks are you referring to that would make sense in check media?

**Comment by RumovZ** [comment]
Sorry, I mixed up Check Media and Database. 🤦‍♂️
What I meant to say: Should I remove the existing blocking template errors and move them into Check _Database_ or even a new routine that checks for logical errors? I personally don't mind them, but if you think they're creating too much confusion and @kleinerpirat as an experienced user also feels bothered by them, I wouldn't mind moving them, either.

**Comment by dae** [comment]
The existing hard checks do have value in preventing new mistakes from being introduced, and bad collections from propagating - my comments above were mainly lamenting the trouble it is push users in the right direction when they've been successfully doing things the "wrong way" already. If we turn the existing ones into warnings in Check Database, I suspect many users will never come across them, and we'd be back to the earlier issues. WDYT?

@kleinerpirat which checks would you be hoping to bypass?

**Comment by kleinerpirat** [comment]
Thanks for considering.

I'm using Henrik's Asset Manager add-on for my card templates and my notetypes tend to have a lot of fields. When I add multiple new card templates in one go (via the Anki template editor), I need to go in and manually edit the field references for each one just to be able to save - otherwise I get this error:

```
Card template ⁨n in notetype '⁨x⁩' has a problem.
The front side is identical to card template ⁨n-1⁩.
```

A similar situation happens in the fields dialog. When I've added lots of fields and adjusted each one by hand, it is really frustrating when Anki doesn't allow me to save, just because of some obscure template error that I can't fix from the fields dialog and which will get overwritten by Asset Manager anyway.

Perhaps these are issues that very few people ever faced, but they've been major obstacles for me at times.

---
### On another note
I've brought this up before in #1716: Batch-editing functionality for fields and templates would be amazing. Even with <10 fields, setting the same value for each one individually doesn't feel right.
