### ISSUE TITLE
Cmd+w to close add window no longer works

### ISSUE THREAD

**Issue by dae** [ankitects/anki#2026]
Caused by making it a main window; we'd need to add an explicit shortcut or a menu item to fix it.

https://forums.ankiweb.net/t/problem-closing-add-window-in-newest-mac-os-version/22423

**Comment by sam1penny** [comment]
> Caused by making it a main window; we'd need to add an explicit shortcut or a menu item to fix it.
> 
> https://forums.ankiweb.net/t/problem-closing-add-window-in-newest-mac-os-version/22423

Since we don't use the return value of the QDialog, would it be safe to replace `.reject()` with `.close()` in addCloseShortcut?
https://github.com/ankitects/anki/blob/45f2502e5b6435c667e3ce0aa57a448b63e16fa2/qt/aqt/utils.py#L843-L848

If so, then I'll open a PR with the modification, and with an explicit shotcut in AddCards :)

I think a menu item would be a bit extreme considering, there would be nothing else in the menu at the minute.

**Comment by dae** [comment]
Maybe we could make another helper that deals with windows instead of dialogs, to avoid potentially breaking any other cases? Whichever approach is taken, we'll also need to ensure a confirmation window is still shown when the user tries to close the window with text in the field.
