### ISSUE TITLE
Dropdown in options screen is too small

### ISSUE THREAD

**Issue by dae** [ankitects/anki#2076]
@hgiesel #2011 reduced the size of the dropdown to the right of the Save button - was that deliberate? The new size is a bit too small to be comfortably tapped with a finger.

**Comment by kleinerpirat** [comment]
I have a PR in the pipeline that changes some elements in the deck options, so I could fix that on the fly.

**Comment by dae** [comment]
That'd be great :-) Are you planning to return to #2046 soon? I'd like to get a beta out soon, and wondering if I should wait for it or not.

**Comment by kleinerpirat** [comment]
That's great news. I was already wondering when the beta might come. The PR I mentioned here is almost finished and will be published tomorrow.

I could get a slightly different solution for #2046 out by the end of the week. Instead of two panes I would resort to a collapse/expand mechanism for the tags, where they're either limited to a single line or fully shown.

**Comment by dae** [comment]
That works for me too - ultimately people just want a way to prevent tags from taking up all their space. Will hang on for that then, and still waiting for a reply from @hgiesel on #2071 anyway.
