### ISSUE TITLE
Command-Delete removes just one word on macOS

### ISSUE THREAD

**Issue by Perlence** [ankitects/anki#2188]
I'm using Anki v2.1.54 Qt6 on macOS 13.0. I've noticed that pressing the **Command-Delete** shortcut on the **Sidebar filter** and **Search cards/notes** text inputs of the **Browse** dialog removes just one word to the left. The expected macOS behavior is to delete the whole line to the left of the insertion point.

The text inputs on the **Add** dialog work fine in this regard. However, I believe, all plain text fields are affected.

![image](https://user-images.githubusercontent.com/1044300/200922070-b8221f7b-b98d-47e9-8d3d-9b23d6a94fc0.png)

**Comment by mahathu** [comment]
Sorry, I don't have time to write a more in depth issue, but I wanted to add that I think this is one effect of an underlying issue. For example, when long pressing a key to show up diacritics (e.g. c -> ç,ć,č), the key that is being held will be repeatedly entered in the text field until the finger is lifted from that key. Expected behaviour would be that text entry stops until the user selects one of the special characters from the menu.

Perhaps the type of input field needs to be changed to resolve all these issues at once?
