### ISSUE TITLE
improve confirmation screen when closing add dialog

### ISSUE THREAD

**Issue by dae** [ankitects/anki#2282]
Yes/no buttons would be clearer as eg. "Discard" and "Keep Editing", and the prompt will probably need to be changed to something like "Discard current input?". This will probably require adding some new translation strings.

https://forums.ankiweb.net/t/saving-changes-to-evaluation-exit/25546

**Comment by chezfo** [comment]
It is important.

I also suggest turning the question around. Instead of "whether to throw away" the question should be "whether to keep". When the answer is "yes". Save and take you out of the editor. (and won't bring you back to save...)

https://forums.ankiweb.net/t/saving-changes-to-evaluation-exit/25546?u=noty

**Comment by dae** [comment]
The user has issued a close action, so I think focusing on what will happen if they proceed (i.e. discard) makes more sense than talking about 'keep'ing.

When we tackle this, we might want to change the default button too: https://forums.ankiweb.net/t/close-and-lose-current-input-default-option-yes/38011

**Comment by chezfo** [comment]
You can make three options as in Word, and other software
 1. Save 2. Do not save 3. Cancel and return to editing.

**Comment by dae** [comment]
Sorry, I don't really see the value in that. "Save" in this context means "Add", and I don't think users are typically going to add a card immediately after they've tried to close the window. Some way of saving a draft would be nice in the future, but that's a separate feature request.

**Comment by chezfo** [comment]
Maybe we're not talking about the same "dialog" box??
 I'm talking about an evaluative exit.  When editing an existing card template.
 When you spend a lot of time editing, you don't always remember that the edit is not saved automatically and you have to click save.
This problem didn't start with Anki.  It is found in every word processor, or graphics editor.
 In all the programs I know, the program offers the option of saving or discarding, or returning to editing.

-  word and all office applications
- PDF-XC
- acrobat adobi
- fine rieder abby
- VScode

and many other programs.  So I see no reason why Enki would behave differently.
 Anyway from your response I understand that we are not talking about the same dialog box.  That's why I'm attaching a picture.
![תמונה](https://github.com/ankitects/anki/assets/85172877/28439225-f33d-4efb-92aa-dea47ce583a4)
