### ISSUE TITLE
Deal with `>` in alt tags

### ISSUE THREAD

**Issue by dae** [ankitects/anki#2304]
A full HTML parser could be a lot slower, so I'd prefer to hold off on that for now if possible or benchmark first. Perhaps a hacky solution for now would be to strip the `>` character from the alt tag on paste? Before 2.1.54, the entire alt tag was stripped, so this is a recent regression.

https://forums.ankiweb.net/t/check-media-bug-symbol-in-alt-attribute/25997/

**Comment by Mudskipper875** [comment]
Since this problem only occurs if the offending attribute is placed before the `src` attribute, could a possible solution be to automatically move the `src` attribute to the beginning of the `<img>` tag?

For example
* `<img title="bad > text" src="pic.jpg">` - **Unused media**
* `<img src="pic.jpg" title="bad > text">` - Works fine


Another solution might be to use the character encoding `&gt;`, but anki seems to automatically decode it while typing in the html editor.

**Comment by bpnguyen107** [comment]
I believe this was fixed in https://github.com/ankitects/anki/pull/2918

**Comment by dae** [comment]
Thanks Ben!
