### ISSUE TITLE
Time doesn't stop when the answer is shown

### ISSUE THREAD

**Issue by mperry2** [ankitects/anki#2309]
When a deck is configured to use a timer, the timer doesn't stop when the answer is revealed.

Expected result: The timer should stop when the answer is revealed.

**Comment by dae** [comment]
https://forums.ankiweb.net/t/timer-is-still-counting-in-between-cards-is-it-normal/20552/5

**Comment by dae** [comment]
The forum seems to have automatically silenced your account because you "typed too fast" - did you maybe paste some pre-written text into a post? I can't see the post in question though, and don't think I got notified about it. What happens if you try to create a post?

I'm afraid I will not be able to accept that patch. The review log is used to approximate total study time and average answer time, and recording only the question portion will break that.

**Comment by dae** [comment]
I'm not sure what's happened on the forum end, but I've manually adjusted your account so you should be able to post there again now.
