### ISSUE TITLE
Investigate non-Latin text wrapping in deck options dropdown

### ISSUE THREAD

**Issue by dae** [ankitects/anki#2316]
https://forums.ankiweb.net/t/anki-2-1-56-release-candidate/26001/30

**Comment by dae** [comment]
@hikaru-y I don't suppose you have an idea why this is happening? I see it when testing in Chrome too, but don't know what's causing it. Adding a min-width to the button seems to work around it, but not sure if there's a cleaner way.

**Comment by winterhazel** [comment]
This is due to importing IconButton.svelte instead of LabelButton.svelte on ts/deck-options/SaveButton.svelte line 13 (wrong import), which doesn't have the white-space: nowrap property. 

I tried changing it, but overflow: hidden breaks the text centering. Removing overflow: hidden fixes it, but allows the leftmost LabelButton on the Change Note Type window to expand indefinitely depending on the previous Note Type's name.

A possible way to fix this would be fixing the import and adding overflow: visible to this button through a class. I'm not sure if that's the best option since I'm not familiar with Svelte though. I'll send a PR with these changes.

**Comment by hikaru-y** [comment]
@dae  Thanks for pinging me. I have just looked into the issue.

I think a common way to prevent button text from wrapping is either of the following:
- `white-space: nowrap;`
- `min-width: max-content;`

Therefore, as @winterhazel pointed out, we can prevent text from wrapping by correctly importing `LabelButton.svelte` which contains `white-space: nowrap;`. However, using `white-space: nowrap;` and `overflow: hidden;` together even when `text-overflow: ellipsis` is not needed, as in that component, can be problematic.

---

@winterhazel 
> I tried changing it, but overflow: hidden breaks the text centering. Removing overflow: hidden fixes it, but allows the leftmost LabelButton on the Change Note Type window to expand indefinitely depending on the previous Note Type's name.

If it were me, I would probably try the following approach:
1. Create an `ellipsisis` prop (`false` by default) in `LabelButton.svelte`, and pass `true` to that prop in `NotetypeSelector.svelte`, etc.
1. Toggle the `ellipsis` class using that prop in `LabelButton.svelte`
1. Modify the `<style>` like the following:
```diff
         white-space: nowrap;
-        overflow: hidden;
-        text-overflow: ellipsis;
+        &.ellipsis {
+            overflow: hidden;
+            text-overflow: ellipsis;
+        }
         padding: 0 calc(var(--buttons-size) / 3);
 ```

**Comment by winterhazel** [comment]
@hikaru-y Thanks for taking a look at this! I've commited your suggestions to my PR.

Everything seems okay now. I've looked at the other usages of `LabelButton.svelte` and they don't seem to need the `ellipsis` prop.
