### ISSUE TITLE
Copyright licensing discrepancy in Logo

### ISSUE THREAD

**Issue by Matr1x-101** [ankitects/anki#2339]
NOTE: I know this isn't a dev task, but I think it's important for the devs to know.

At [https://web.archive.org/web/20120715052539/http://phatcore.com/portfolio/logos.php](this website,) which appears to say "(c) Alex Fraser" (who commissioned the logo), it shows the logo as being licensed under **GPL-2.0**. Your "LICENSE" file in the root of this repo stated that the logo is copyright Alex Frasier, and it is **AGPL-3.0**

So, is the logo GPL-2.0 or AGPL-3.0?

**Comment by dae** [comment]
The license of the file in Anki's repo was changed in 2012 with Alex's permission.

**Comment by Matr1x-101** [comment]
@dae the GPL is non-revocable; you can't change/undo it. ease change the LICENSE file to reflect that.

**Comment by Matr1x-101** [comment]
This means it **must** be dual-licensed under GPL-2.0+ and AGPL-3.0+.

**Comment by dae** [comment]
A sole copyright holder is entitled to vary the license they distribute their work under as they please. What they can't do is invalidate or retroactively alter the license granted to users who obtained the file under the GPL2, and that has not happened here.

**Comment by Matr1x-101** [comment]
@dae so do you agree that the logo is GPL and AGPL? Because the GPL is non-revocable; if you say a work (in this case a logo) is GPL, it will be GPL (you can't change that) until it enters public domain. 

Also, I'm sorry if I sound like a douchebag. Just a Wiki(p/m)edia editor who wants to know if there are any issues with copyright.

**Comment by dae** [comment]
If the user obtained a logo file that was licensed under the GPL2, that license is irrevocable. It does not extend to future work though - any updates made to the logos since 2012 (eg any design tweaks and images with different dimensions) were only released under the AGPL. "Dual-licensed" implies the user can pick the license they want, but that's not the case here - the license used for distribution was changed, so users who want it under a GPL2 license are limited to content distributed prior to the license change date.
