### ISSUE TITLE
Editor performance has regressed

### ISSUE THREAD

**Issue by dae** [ankitects/anki#2344]
Users have reported the loading notetypes with lots of fields is noticeably slower than it was in 2.1.54. One such example: https://forums.ankiweb.net/t/2-1-55-image-size-problem-in-editor/25507/20. A good first step would be to do some profiling and figure out where the bulk of the time is being taken up.

**Comment by rwmpelstilzchen** [comment]
I’m not familiar with the code, but [one line](https://github.com/ankitects/anki/commit/03fe2385efb00dcbcd513f9cc5bb1b9fdea91972#diff-9845b61a8419c9434804c66e27e677c11026d7973c34ec8b24a4a25f6126cf09R63) caught my eye. If it awaits for every single field, an unnoticable delay for a few fields can become noticable with many fields. I can’t check if this is really the cause because my machine refuses to build Anki properly (this is an unrelated issue; the problem is definitely on my side), but I wouldn’t be surprised if the cause is something that happens for every field.

**Comment by dae** [comment]
Commenting it out does not appear to make a difference

**Comment by rwmpelstilzchen** [comment]
Thanks for checking this :-)

For the moment, a possible cumbersome workaround is to let the editor and browser windows stay open, so editing/browsing the same note type multiple times doesn’t require waiting each time.

**Comment by rwmpelstilzchen** [comment]
Just a small bit of information that may help in the diagnosis: when I run `htop` I see a peak in CPU usage when the edit/browse/add screen is loading with many fields (I suppose the same occurs with a few fields, but it is just shorter). This explain [this case](https://forums.ankiweb.net/t/anki-2-1-57-beta/26494/72), in which a note-type with 92 fields takes 20 seconds (!) to load on a slow machine.
