### ISSUE TITLE
Our clipboard handling code seems to cause issues

### ISSUE THREAD

**Issue by dae** [ankitects/anki#2349]
_flagAnkiText() is called when text is copied to the clipboard. It inserts `<--!anki-->` at the start of the HTML in the clipboard, so that if the text is later pasted back into Anki, we know we can bypass the usual formatting that is applied. Unfortunately this seems to lead to race conditions when we write to the clipboard shortly after a cut/copy operation, especially with some Linux WMs and when clipboard managers are running on Windows. Maybe we could rework the code to be less likely to cause problems, or maybe there's a better way to accomplish this - suggestions welcome.

Latest thread: https://forums.ankiweb.net/t/browser-freezing-when-copying/25240/12

**Comment by tomkahn** [comment]
Maybe instead of writing to the clipboard you could simply read the clipboard content and retain a copy of it in a variable. If the user then pastes something into Anki later on you simply compare it to this variable and if it is identical you also know that you don't have to reformat anything. Is applying the formatting such a compute intensive process that this is necessary in the first place, though?

**Comment by dae** [comment]
It's not because we're trying to save compute, it's because HTML from external sources needs filtering, but we don't want to strip formatting when the user copies things between fields, or they may lose formatting they've deliberately added. Noting the current contents down might be a good alternative solution.

**Comment by tomkahn** [comment]
Ah, I see, that makes sense. Yeah, I guess retaining a copy of all the field contents when the user presses Ctrl+C would be even better since you don't access the clipboard at all. Then on paste you could compare if whatever is being pasted is either equal to one of the fields or even just a part of one the fields, in which case stripping formatting would be unneccessary.

**Comment by ewollesen** [comment]
Oooh, so glad to see this (hopefully) fixed up. I've installed the latest beta build and will report back. Thanks!

**Comment by ewollesen** [comment]
> Oooh, so glad to see this (hopefully) fixed up. I've installed the latest beta build and will report back. Thanks!

Working great, plenty of cuts, copies, and pastes, and no more freezes!

I tested with:

```
Version ⁨2.1.66 (46915605)⁩
Python 3.9.15 Qt 6.5.0 PyQt 6.5.0
```

Running in Linux (Ubuntu 22.04), X11 with the i3 window manager, and xfce4-clipman for clipboard management.
