### ISSUE TITLE
Some users report that the bottom bar is missing until 'reduce motion' is turned on

### ISSUE THREAD

**Issue by dae** [ankitects/anki#2411]
Eg

https://forums.ankiweb.net/t/missing-scheduling-boxes-after-21-160-qt6-update/28003

https://forums.ankiweb.net/t/unable-to-see-bottom-row-information-on-desktop/28078

Any ideas @kleinerpirat?

**Comment by dae** [comment]
Some other users report that adjusting 'hide bottom bar' seems to fix it:

https://forums.ankiweb.net/t/no-buttons-at-bottom-of-page-to-check-answer/28185

**Comment by 7MinutesDead-Git** [comment]
I want to confirm I'm also seeing this on my end on Windows 10, Anki Version ⁨2.1.60 (76d88073)⁩ 

When I click "Study Now" button on any deck, the bottom button bar then animates/slides down and out of view.

If I disable animations with "Reduce motion", since the animation never plays, the buttons never disappear.
If I toggle on "Hide bottom bar during review" set to "Full screen only" while not in fullscreen, that also makes the buttons come back.

So, it's as if "hide bottom bar" is on by default for windowed mode, or something.

**Comment by dae** [comment]
Hiding defaults to off, and I can't reproduce this on a system here, so I'm not sure at the moment what's causing this.

**Comment by 7MinutesDead-Git** [comment]
I'll keep exploring and see what I can find. I can at least test on Windows 10 and Windows 11

**Comment by freesimple** [comment]
I also have this problem, whether Windows 11 or Mac.

**Comment by dae** [comment]
Whether or not the hide bottom bar and reduce motion options are enabled? You see no answer buttons? Does disabling add-ons help?

**Comment by freesimple** [comment]
Yes,when I reduce motion options, will not have this problem.

**Comment by dae** [comment]
I haven't heard any recent reports of this (that I remember anyway) - perhaps we must have fixed it when we removed some of the default animations? Closing until we get a new report.
