### ISSUE TITLE
Investigate switch from node to deno

### ISSUE THREAD

**Issue by dae** [ankitects/anki#2439]
Some issues we're likely to hit that will need investigating before it becomes practical:

- Ensuring we can still edit Svelte files in VS Code with proper code completion/checking
- Ensuring we can still build Svelte files and use svelte-check in CI.
- Figuring out if it's possible to port our existing Jest tests over to Deno's test runner. Some of our tests rely on jsdom.
- Ensuring protobuf generation still works. We could potentially fall back on #2043 if protobufjs proves problematic, and I have a half-complete port lying around somewhere.
- We copy files from node_modules as part of the build; that will no longer work with deno AFAIK, and we'll need to manually pull the files from npm packages. I have a prototype implementation that does this.

Related: #2430

**Comment by andrewpeters9** [comment]
Happy to take this on if you'd like me to as I have decent availability - feel free to assign it to me if you're comfortable with me taking this on.

Just some other trivial things I think could be added to the checklist:

- [ ] Ensure all Node packages used have a Deno Package (this was previously an issue with packages such as `mongoose` etc.)
  - [ ] For those that don't, evaluate workarounds
- [x] Ensure that `deno` packages can be patched 
  - [x] Appears that `deno vendor` can help with this - https://deno.land/manual@v1.31.2/tools/vendor
- [ ] Ensure WebStorm IDE support for those using Intellij editors
- [ ] Quickly hack up small pieces of the conversion to uncover unknown-unknowns that may pop up

**Comment by dae** [comment]
If you'd like to look into this, that would be much appreciated. A couple of points:

- the VS code configuration is in .vscode.dist, and I think the other devs are using it too
- I found Svelte support in IDEA to not be very good in the past, but perhaps things have improved or I had set things up wrong.
- I'd prefer not to have protobufjs files directly in the repo, but we should be able to put them in a submodule and then use vendor with that.

**Comment by andrewpeters9** [comment]
Took a bit of look today. 

* `svelte` IDE integration seemed to work in VS Code with the Deno plugin installed and `"deno.enable": true,` added to `.vscode/settings.json` (as well as in WebStorm) - but this may be a different story when `node` is completely ripped out
* `esbuild` seems to generally work OK with `deno` granted some small changes
  * This is not the case for some plugins however, e.g. `esbuild-sass-plugin` - this can be fixed by using this however: https://github.com/LePichu/esbuild-plugin-sass-deno
* `deno` respects `package.json` which alleviates some of the pain in conversion, it doesn't however respect `yarn.lock`
  * E.g. `deno` will go ahead and use `esbuild@0.15.18` as it's the latest version that complies with `package.json`, but this doesn't comply with `yarn.lock` which requires `^0.15.13` to resolve to `0.15.13`
    * I have a couple of ideas in mind for a fix, not a show stopper - but may involve either strict versions or resolutions built into the `package.json`
* Have yet to investigate protobuf and Jest test migration. Will look into that when I have the time to.
* I'm also coming across some things such as `yarn.sh` that will have be written etc. Deno integration might be something that coexists with `node` for a while and then `yarn` and `node` could be slowly phased out - up to you though.

**Comment by dae** [comment]
Thanks Andrew.

Currently package.json is rather lax compared to the lock file; after 2.1.61 is released (hopefully not long) I'll do a dependency bump and update package.json at the same time so they're closer in sync.

I don't mind a temporary period where we have both node and deno being used, as long as there's a clear path to full migration. What would not be ideal is if the deno migration stalls, and we end up stuck requiring both of them.

**Comment by andrewpeters9** [comment]
@dae Gotcha. I'll dig deeper into these testing Jest and protobuf issues over the weekend - although I may need a hand with ascerning if protobuf will still work, as I'm new to Rust + protobuf.

I'll also start to put together a list of tasks required, and how they could be potentially batched up.

**Comment by dae** [comment]
A smoke test for the protobuf code is opening the graphs screen - the graphs will fail to render if protobufjs is not working. If you run into an issue with it and need help, please let me know.

**Comment by dae** [comment]
No rush - this is not a blocking task. Appreciate your contributions.

**Comment by andrewpeters9** [comment]
Hey @dae , I'm still wanting to do this, have just been smashed at work recently. Jumped back on this over the weekend, here's what I've found/did:

**Some recent developments to Deno:**
* Support for `node_modules`
  * Makes transition for some Rust steps easier
* Dependencies from `npm` can be directly pulled in by `npm:`
  * This isn't to say that all `npm` deps will work out of the box, however. 
* [Support for lock files](https://deno.land/x/deno@v1.32.3/cli/schemas/config-file.v1.json?source=#L417)
  * But, it doesn't support `yarn.lock` files. Potentially there's some script that will convert `yarn.lock` to `package-lock.json`
    * This is also dependent on how precise you are with your lock file. E.g. do you just rebuild lock files frequently, or are you always trying to keep the lock file as lean as possible
    * We could potentially just recreate the lock file with Deno (Deno has a native lock file called `deno-lock.json` and we could optimise from there?
* [Support for local references in package.json](https://github.com/andrewpeters9/anki/pull/1/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R65-R79)

 **General work:**
* I got a compile working for the easiest ESBuild scripts, the task can be run via [this task](https://github.com/andrewpeters9/anki/pull/1/files#diff-54337bcff4b919f6b8b4e0b0e51d06fd9124562fde88899be726c24b7e354b7cR5)
  * I haven't tested the validity of this build, but I'll do so when I get around to running a full build
* Jest appears to be an issue, but given that there aren't a tonne of Jest tests, maybe they could just be rewritten in Deno's native testing library (fairly similar syntax to Jest)
  * This might also be a good MR to first introduce Deno in via? I.e., just strip out Jest and replace with Deno testing, but leave everything as is
* `svelte` intellisense appears to be an issue (at least for me on WebStorm, I'll try VSCode soon)
  * Problem lies with non-default exports from `<script context="module"></script>`
  * This problem existed with TS when `svelte` came out and has since been resolved
    * I wonder if, assuming a cleaner solution can't be found, is to have a separate TS instance in one's IDE - and just leave the `tsconfig.json` files in their respective folders (even though Deno will ignore these)
 * There are some intricacies in some subfolders. I've left the `tsconfig.json` files undeleted that I think may be problematic. I'm guessing the solution may be to just pass some of these special `tsconfig.json` configurations through ESBuild (assuming that intellisense is fine without it - which is kind of appears to be, with the exception of `svelte` module exports

**Comment by dae** [comment]
Thanks for all your work on this Andrew.

Jest pulls in quite a lot of transitive dependencies IIRC, so if it's practical to replace with Deno's built-in runner, that would be a nice win. Some of our Jest tests use it with the jsdom environment, so we can run tests against browser APIs (eg ts/html-filter relies on document.getElement() & .nodeType), so we'd need some way to still support those APIs (maybe deno-dom + some reworking of the tests?).

Re lock files, in larger Anki updates, I try to update all deps to their latest. In smaller updates, I want the versions to be locked, and the ability to update single deps (eg pull in a security update to a package without updating everything else). I presume such a workflow can be done using the traditional Deno approach of listing out versions in a dependencies.ts file, which the rest of the codebase imports? A move to deno would come as part of a larger update, so I'm not too concerned about matching the existing yarn lockfile. I briefly Googled the deno lock documentation, but it seemed pretty barebones - I'm guessing it doesn't currently provide something akin to 'yarn upgrade' or 'yarn upgrade some_package'? 

I gave the math-jax task a try using your PR, and was initially surprised at how slow deno was to pull in all the packages, but then I realised that I'm just used to yarn runs where the packages have already been cached.

Re `@tslib` imports in VS Code, while we could reference the non-generated files via relative paths instead, all our protobuf code and translations are also referenced that way, so we'd definitely need to fix this before a switch is practical.

I'm open to starting with deno as just a Jest replacement, once we've at least prototyped using it for our other components and/or can easily roll it back. What I'd like to avoid is a situation where we've partially switched to deno and then discovered showstopper issues that require us to keep using yarn, and we're unable to roll back deno either, leaving us with a build system that is twice as slow :-)

**Comment by andrewpeters9** [comment]
> Jest pulls in quite a lot of transitive dependencies IIRC, so if it's practical to replace with Deno's built-in runner, that would be a nice win.

Sounds like a good MR to start with. I'll start work on this over the weekend.

>  I presume such a workflow can be done using the traditional Deno approach of listing out versions in a dependencies.ts file, which the rest of the codebase imports?

Correct

> I briefly Googled the deno lock documentation, but it seemed pretty barebones - I'm guessing it doesn't currently provide something akin to 'yarn upgrade' or 'yarn upgrade some_package'?

For upgrading all packages in one command, I'm unsure if this exists, but individual packages can be updated while still being careful not to disrupt the lockfile. So I don't think there's a problem here.

> I gave the math-jax task a try using your PR, and was initially surprised at how slow deno was to pull in all the packages, but then I realised that I'm just used to yarn runs where the packages have already been cached.

Necessary packages are cached upon the first call to `deno`, so subsequent builds should be a lot quicker. Feel free to re-run that command to check the speed - as I don't want your workflow to be impacted by a command that I imagine you're running plenty of times a day.

> I'm open to starting with deno as just a Jest replacement, once we've at least prototyped using it for our other components and/or can easily roll it back.

Sounds good to me!

**Comment by dae** [comment]
> For upgrading all packages in one command, I'm unsure if this exists, but individual packages can be updated while still being careful not to disrupt the lockfile. So I don't think there's a problem here.

Having to manually update all packages would be rather cumbersome, and I'm a bit surprised they don't provide a first-party solution for this, but it looks like https://github.com/hayd/deno-udd will accomplish it.

> so subsequent builds should be a lot quicker.

Yep, they are :-)

**Comment by dae** [comment]
Closing, as it was determined that it's not practical for now.
