### ISSUE TITLE
Problem with Qt6 but not with Qt5

### ISSUE THREAD

**Issue by shundred** [ankitects/anki#2459]
I just installed windows 10 1511 (updated), after that I installed 2.1.60 qt6

It showed for a second in task manager and closed automatically without even error message or any sign of Anki window at all

So I took help of AI, it asked me to do many things after which this is what I got in cmd

C:\Program Files\Anki>anki-console
Anki starting...
Initial setup...
Running with temporary Qt5 compatibility shims.
Run with DISABLE_QT5_COMPAT=1 to confirm compatibility with Qt6.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "aqt", line 46, in <module>
  File "aqt.gui_hooks, line 11, in <module>
  File "_aqt.hooks", line 18, in <module>
  File "aqt.gt", line 20, in <module>
  File "aqt.qt.qt5_compat", line 17, in <module>
ImportError: DLL load failed while importing QtGui: The specified procedure could not be found..

I am calling it a bug because then I installed 2.1.60 qt5 and it worked fine

If not help me fix this

**Comment by NameLessGO** [comment]
windows 10 1511, latest version was in 2017, update your system to [22H2](https://www.wikiwand.com/en/Windows_10_version_history)

i have this problem in my uni pc because it is an older system, prob the same as yours

it's not a problem on anki side (would love to have a fix or workaround though), your windows from 2017 can't use Qt6 which is from ~2020

**Comment by dae** [comment]
Apparently we could do a win10 version check with NSI, like so:

```
!include LogicLib.nsh
!include WinVer.nsh

Function .onInit
    ${If} ${AtLeastWin10}
        ; Check build number for Windows 10, version 1511 or later
        ${If} $WINDOWS_BUILD >= 10586
            ; Compatible version, proceed with installation
        ${Else}
            MessageBox MB_OK|MB_ICONEXCLAMATION "This application requires Windows 10, version 1511 (Build 10586) or later."
            Quit
        ${EndIf}
    ${Else}
        MessageBox MB_OK|MB_ICONEXCLAMATION "This application requires Windows 10, version 1511 (Build 10586) or later."
        Quit
    ${EndIf}
FunctionEnd
```

That said, since it's not clear the minimum build that will actually work with Qt, we risk introducing a regression here. And since this issue has only come up once to my recollection, I think we're probably better off not doing anything about it.
