### ISSUE TITLE
Toggle Masks and Back Extra can't be seen on small screens

### ISSUE THREAD

**Issue by dae** [ankitects/anki#2477]
@krmanik no rush; don't let this interrupt your studies

It looks like currently 'toggle masks' and 'back extra' can't be seen when reviewing on mobile, as the container is being resized to the original image size, so the user has to scroll past a bunch of blank area to see it:

<img width="393" alt="Screenshot 2023-04-19 at 2 47 58 pm" src="https://user-images.githubusercontent.com/180542/232969617-0c3efd71-73c0-4b53-a28f-b033f33b16e1.png">
<img width="408" alt="Screenshot 2023-04-19 at 2 48 08 pm" src="https://user-images.githubusercontent.com/180542/232969634-67e730cb-4324-41a2-8f3e-9cf7c8039ea9.png">

I've made some minor tweaks to the code as I work on integration, and will push them in the next day or two.

**Comment by krmanik** [comment]
When image first loaded in reviewer then it shown properly but when it updated, its height change.

To test.
1. Add image occlusion notes
2. Open edit card in Back Side of reviewer
3. Click preview, the toggle button is at correct position
4. Now flip twice the position changed.

I have tried to debug it, but I don't understand where the issue is. I will update it after finding the solution. The PR may not solve the issue.

The values are height, clientHeight and naturalHeight in the image.

<img src="https://user-images.githubusercontent.com/12841290/233713563-83927fac-800d-443c-9e11-0ac1fc109748.png" height="450px">

**Comment by glutanimate** [comment]
@krmanik just out of curiosity, what tool were you using in that previous screenshot to debug the iOS web view?

**Comment by krmanik** [comment]
https://github.com/ankidroid/Anki-Android/wiki/Development-Guide#via-eruda-console-for-mobile-browsers

**Comment by glutanimate** [comment]
🙏 Appreciate it, thanks! I faintly remember trying eruda on AnkiMobile in the past, but not managing to get it to work back then. Cool to see that it does actually work, will have to give it another try

**Comment by krmanik** [comment]
The solution is to again call function `anki.setupImageCloze();` in backside of reviewer in iOS. Because it does not update the image load.

May one more event listener can be added in here for iOS in `image_occlusion.ts`.

```js
window.addEventListener("load", () => {
    window.addEventListener("resize", setupImageCloze);
});
```

Before clicking setup button and after clicking setup button, so I think the `setupImageCloze` is not called in back side of reviewer.

<img src="https://user-images.githubusercontent.com/12841290/233756937-f8389d1e-854b-46d2-a1a0-95c6184d9ab5.png" height="450px"> <img src="https://user-images.githubusercontent.com/12841290/233756935-365950e4-cf9a-42e0-87f4-4e2e627506a3.png" height="450px"> 
https://krmanik.github.io/test-ios

**Comment by dae** [comment]
Didn't know about eruda - neat! Original issue continued on https://github.com/ankitects/anki/pull/2480
