### ISSUE TITLE
New importer creates new copy of remapped notetypes on each import

### ISSUE THREAD

**Issue by dae** [ankitects/anki#2482]
When we encounter a notetype schema conflict in .apkg import, we add the incoming notetype with a new id. This happens each time the file is imported, so if the user imports the file multiple times, they end up with a bunch of duplicate notetypes.

The way the original importing code handled this is to add remapped notetypes with an incremental id, and reuse an existing one with a matching schema. I briefly brought this up on https://github.com/ankitects/anki/pull/1743#issuecomment-1082569967, but it looks like we may have forgotten about it.

Ideally, we would reuse a previous remapped notetype if available, as if the user has a workflow that involves regularly importing updated versions of the shared deck, they'll end up with lots of different notetypes.

**Comment by RumovZ** [comment]
I don't quite remember, but maybe we skipped that because we planned to do something more sophisticated with notetype conflicts?
Anyway, what if we add an `original_id` to notetypes? Then if we try to import a notetype and it has a different schema than the existing noteype with the same id, we could check if there is an unconflicting notetype with a matching `original_id` next. If there isn't we would add the notetype with a remapped id like before, but remember its original id.

Regardless, I'm still interested in implementing automatic conflict resolution. As a first step, do you mind assigning ids to fields and templates? It would allow us to determine the cause of a conflict (e.g. whether a field was renamed, moved, added...) and merge notetypes accordingly.
Maybe this could even be leveraged for syncing, where notetype schema changes are also a pain in the neck?

**Comment by dae** [comment]
If original_id & ids in fields/templates are the best path forward I'm ok with adding them, but I'd like us to talk through how it would work a bit first.

The ids will only help users who import a deck for the first time after updating to a version of Anki that adds these ids. That may be unavoidable, but ideally we'd have a solution that would work for existing users as well. Maybe we could fall back on simple name matches if ids are unavailable?

Automatic conflict resolution would be nice, provided we can be confident that the way conflicts are resolved is what most/all users would expect. I don't have any data on this, but I'm assuming the most common source of conflicts is changes to the names, order or number of fields. How would you see things being handled automatically in the following scenarios?

Let's assume the initial import has Front/Back/Extra fields.

- Exporter adds another field. Do we throw away the contents of that field when updating existing notes?
- Exporter removes a field. Do we leave the existing contents alone when updating notes?
- Exporter renames Extra->Other. With ids we can detect this; without, do we ignore the potentially updated Other field and leave the existing Extra contents alone?

Since in some cases we wouldn't be fully updating the notes, perhaps we would need some way to signal to the user where certain content has been skipped?

How do ids solve the notetypes-keep-increasing problem if the notetype to import doesn't match the one in the collection?

**Comment by dae** [comment]
> You mean like the status quo? Definitely.

I was thinking more of changes to fields/templates here, not differing notetype ids. The status quo requires all field names to be identical and in the same order; what I was thinking of was that the fallback would be each field would be matched based on its name individually (but done once per notetype so we don't need to do string comparisons for every note)

> I would add the field to the notetype. Why wouldn't we?
> I would remove the field. Presumably, the deck author had their reasons.

That would require a change notetype operation on any existing notes using that notetype that weren't updated or don't exist in the incoming collection - eg a user added their own cards using a notetype that originally came from a shared deck.  We're thus potentially changing notes unrelated to the import, which users may find confusing or unwanted.

The examples I gave above focused on changes the exporter made, but the same could apply to any changes the importer made in the past (eg adding another field for personal notes that didn't exist in the original notetype). Erasing that field and its contents on import would not be desirable.

One problem with the "ignore missing fields" approach I mentioned in my previous post is that if we import template updates, and those templates reference the missing field, it's going to lead to errors unless we also strip the field reference out.

**Comment by RumovZ** [comment]
>  the fallback would be each field would be matched based on its name individually

Yes, I guess this would work for simple changes, like reordering fields and adding a new one.

> That would require a change notetype operation on any existing notes using that notetype that weren't updated or don't exist in the incoming collection

You're right. Maybe if the user could decide the conflict resolution strategy like _Merge_, _Skip_, _Duplicate_ and its consequences would be explained in a tooltip it would be acceptable?

> (eg adding another field for personal notes that didn't exist in the original notetype). Erasing that field and its contents on import would not be desirable.

No, the idea is to keep the union of fields of both notetypes.

However, templates and styling will always pose a problem and require manual work. Do you think that's a showstopper?

**Comment by dae** [comment]
> Maybe if the user could decide the conflict resolution strategy like Merge, Skip, Duplicate

My initial reaction is that 'Duplicate' feels like it might be a bit of a footgun, potentially leading to users who are confused when they have two slightly-different copies of notes, or who are unable to apply updates because they previously duplicated notes. In its defense, we already offer such an option for CSV imports though, so maybe I'm overthinking things. And there have been cases where users have wanted such an option because they want to import the same material multiple times and then modify it.

One potential downside of popups is that if the .apkg file contains a bunch of different notetypes, that's potentially a number of different popups, and the user may have to deal with them frequently if they're frequently importing updates. One potentially simpler but less flexible alternative would be to take an approach like the CSV import - have the options shown up-front, and apply to everything that's being imported. This would probably mean .apkg imports now have a confirmation step, but I'm not sure that's a bad thing.

> However, templates and styling will always pose a problem and require manual work. Do you think that's a showstopper?

I hope whatever solution we come up with doesn't potentially cause either existing notes nor newly-imported notes to display template errors when imported, as that's both a bad user experience, and a support nightmare :-)

One downside of changing existing notetypes is that it will force a one-way sync, which is a fair bit more resource intensive on AnkiWeb. This may be unavoidable in the case of conflicts, but it will hopefully at least be idempotent - a subsequent import of an .apkg file whether neither side has changed the notetypes shouldn't trigger another conflict.

**Comment by RumovZ** [comment]
Yeah, at least for the start Merge (auto resolution) and Skip (current behaviour) should suffice.

> have the options shown up-front, and apply to everything that's being imported.

I actually had that in mind. It could be refined further at a later stage.

> I hope whatever solution we come up with doesn't potentially cause either existing notes nor newly-imported notes to display template errors when imported

That should be rather rare when using the union of notetypes' fields. The only case I can think of right now is if the exporter removed a bunch of fields, added completely new ones instead, and changed the templates accordingly. Then the importer's existing notes would show empty.

Idempotency is a must. But I recall that you said updating the sync protocol is on the agenda once Ankidroid has adapted the Anki backend. 😃

<hr>

The discussion so far was about merging notetypes. Surely original notetype ids are less controversial. It would basically bring back the behaviour of the old importer, only instead of guessing that a previously remapped notetype has a consecutive id (with regard to the conflicting notetype), we would remember the id when remapping.
The original id would also serve as a marker for imported notetypes. E.g. we could warn users about potential future conflicts if they change the schema of such a notetype.
Does this sound good to you?

**Comment by dae** [comment]
Thanks for talking it through with me. The approach you've proposed sounds reasonable, and happy to proceed with the original ids.
