### ISSUE TITLE
Changes not being synced when shutting down PC

### ISSUE THREAD

**Issue by MonsterDruide1** [ankitects/anki#2577]
Anki automatically syncs cards/changes when closing the program, which works just fine, when ... closing the program.

However, when the user decides to not properly do a sync or close the program, but instead just shuts down the whole PC without manually closing the program first, no final sync is happening.

This is quite easy to reproduce:
1. Sync a second device using AnkiWeb
2. Make sure they are on the same version (sync both repeatedly until no changes are done)
3. Do a change on the first device, do not sync manually
4. Shut down the PC without doing another sync
5. Sync the second device, see that no changes have happened
6. Only when booting the first device and manually doing a sync again, the second device can receive the change from step 3.

Expected behaviour:
Just as when manually closing the program, it should do a final sync on shutting down the whole device, instead of just cutting off and keeping the changes locally-only.

I'm not sure which OSes this actually happens with, I just tested with Windows - feel free to comment/add labels if other systems are affected as well.

**Comment by evandrocoan** [comment]
I am not sure anki should sync things when shutting the computer down because, well, the computer is shutting down. It's closing network connections, open programs, etc. To do this, anki should intercept the Windows shutdown signal and tell Windows to wait until anki does its thang, which will delay how much time Windows takes to shut down, and the user may select to force shutting down without waiting for anything. 

Disregard my opinion about this feature, If anyone is interested in doing this, it should not be difficult to implement.

**Comment by MonsterDruide1** [comment]
That's true, but a lot of other programs also already stop/intercept the shutdown to properly do their closing cleanup, so ... why shouldn't Anki do this? It also does so when simply closing it, and closing+shutdown in quick succession will also interrupt the shutdown for some time, until the sync is finished.

**Comment by dae** [comment]
This seems to be a Windows-specific issue, as it already happens on macOS: https://forums.ankiweb.net/t/can-anki-please-stop-preventing-shutdown-for-the-computer/42191
