### ISSUE TITLE
Add styling to cloze deletions inside MathJax

### ISSUE THREAD

**Issue by dae** [ankitects/anki#2650]
https://forums.ankiweb.net/t/feature-request-automatically-add-a-css-class-to-cloze-deletions-in-mathjax-like-in-normal-text/34034/2

**Comment by sandersantema** [comment]
This change hasn't been made as of yet correct? I believe this would also resolve a previous [issue](https://forums.ankiweb.net/t/change-color-of-cloze-inside-mathjax-formula-using-anki-2-1-57/27479/6) I had. Whenever this change goes in (if it isn't already) I'd be willing to test it out. Is [cloze.rs](https://github.com/ankitects/anki/blob/main/rslib/src/cloze.rs) the only place where something needs to change? I've got some experience with Rust and nom so in that case I might take a look myself.

**Comment by dae** [comment]
Yes, that's correct, and I think it's probably just cloze.rs. A PR would be welcome!

**Comment by sandersantema** [comment]
I've had a look at the code. If I'm not mistaken clozes in math (i.e. wrapped in `\(\)` and such) are not treated any differently than those in other text. Which is reflected in the `Token` enum as there is nothing distinguishing tokens in math from those in other text. Is this correct?

Since clozes in math would need to be treated differently my first hunch would be to change the code to start distinguishing between clozes in math and those in text. Do you see any problems with such an approach or have you got one better in mind before I start implementing this?

Another reason for treating clozes in math differently is that they're not displayed correctly if they're in a sub- or super-script:

```
Correct:
\(x^{ {{c1:: y}} }\)
\(x^{ {{c1:: y :: foo bar}} }\)
Incorrect:
\(x^{{c1:: y}}\)
\(x^{{c1:: y :: foo bar}}\)
```
Resulting in:
![image](https://github.com/ankitects/anki/assets/21057514/21877a46-8489-4aab-a1ae-85e6bf5116ba)

I think both the styling and this issue would require distinguishing clozes in text from those in math.

**Comment by dae** [comment]
The clozes first get rendered to HTML, and then strip_html_inside_mathjax() removes any HTML inside MathJax blocks, so only [...] remains. To treat the text in MathJax differently, I guess you could do two replacements, once only inside MathJax blocks, and then again for any remaining cloze deletions. reveal_cloze() could be altered to take in a renderer trait that was responsible for writing out the existing HTML, or alternatively, the text to go inside MathJax.

> not displayed correctly if they're in a sub- or super-script

Are you proposing to always wrap the text in {}, or to try and detect the particular context the cloze is in? The latter sounds like it might get complicated.

**Comment by sandersantema** [comment]
> To treat the text in MathJax differently, I guess you could do two replacements, once only inside MathJax blocks, and then again for any remaining cloze deletions. reveal_cloze() could be altered to take in a renderer trait that was responsible for writing out the existing HTML, or alternatively, the text to go inside MathJax.

If I understand correctly you also think the distinction should be made,  but I would propose a different way of doing this.

1. Extend `Token` enum to include `{Open,Close}Math`
2. Extend `tokenize` to parse the added token variants
3. Extend `ExtractedCloze` with a `in_math: bool` property
4. When looping through tokens in `parse_text_with_clozes` set a flag `in_math` (by which a mean local to the function, not the `ExtractedCloze` property), to true when encountering a `OpenMath` token and vice versa for `CloseMath`
5. Set the `in_math` property of any cloze encountered to the value of the `in_math` flag
6. Change behaviour as needed based on this flag in `impl ExtractedCloze` and `reveal_cloze`. If it would be desired -- hard to say as its a stylistic concern -- you could for instance output `\ldots` instead of `...` if `in_math` is true as it would then render as a proper ellipsis.

I'm not particularly set on the naming or datatypes used, but this should hopefully express my intent.
I personally think it might be better to not use the boolean flag `in_math` for `ExtractedCloze` but rather an enum,
that way it could be extended if specialized behaviour is needed for other things as well. For example:

```rust
enum Context {
    Mathjax,
    Text,
    Latex
}
```
Again, I'm not set on any particular naming.

**Comment by sandersantema** [comment]
> Are you proposing to always wrap the text in {}, or to try and detect the particular context the cloze is in? The latter sounds like it might get complicated.

I thought of it as an argument for making a distinction between clozes in math and those not, and I indeed thought it would be nice to solve this problem too. I believe the main disadvantage of unconditionally wrapping clozes in math with {} is that it messes up spacing of the cloze in rendered math.

But if that's acceptable and there are no other edge cases (although I'm doubtful about that) I think it might be a good choice, but yes otherwise it would probably get (too) complicated.

**Comment by dae** [comment]
Re: tokenizing/using in_math: that approach sounds fine to me, and more efficient.

Re: a blanket {} wrap - could you give me an example of a spacing issue? I don't have a lot of experience with MathJax.

**Comment by sandersantema** [comment]
I think I've almost got a POC done, I'll try and open a draft pr asap. For now I've tried to only add code, although I think the code would benefit from some refactoring and generalization too as it would be hard to keep it tidy and extend it even more. In my POC I've for instance opted to leave out the non-inline math delimiters `\[\]`. 

There also seems to be some duplication of work, first tokenizing `::` for instance and then again splitting a string on it in `parse_text_with_clozes`, I think it should be possible to do all the work in the tokenizing stage. I hope to get around to that if I've got some more time, but for now the I'll try and finish the POC.

Regarding the spacing issue, my knowledge is a bit shoddy and mostly transplanted from latex but AFAIK if you delimit something with `{}` it is seen as a separate thing (I'm missing the right terminology here) and it changes the spacing.

Maybe it's best to show an example:
``` latex
\(\exp (x)\)
\(\exp {(x)}\)
```
Gives us:
![image](https://github.com/ankitects/anki/assets/21057514/0d5429f8-a090-471a-ac67-627a01695a45)

As you can see surrounding `(x)` with curly brackets causes a change in spacing.

**Comment by dae** [comment]
How did you go?

**Comment by sandersantema** [comment]
Unfortunately I haven't had much free time lately. Although I'd like to pick this up again when I've got more time I couldn't make any promises about when that would be. I wouldn't mind anyone else working on it and I'd be willing to give my input or ideas, that shouldn't take much time.

**Comment by MalcolmAnderson** [comment]
> Correct:
> \(x^{ {{c1:: y}} }\)
> \(x^{ {{c1:: y :: foo bar}} }\)
> Incorrect:
> \(x^{{c1:: y}}\)
> \(x^{{c1:: y :: foo bar}}\)

may or may not be related, but I'm seeing many places where the formatting is correct, but the color is black, not blue.
should that be a separate issue?

**Comment by sandersantema** [comment]
> may or may not be related, but I'm seeing many places where the formatting is correct, but the color is black, not blue. should that be a separate issue?

Afaik, the text you quoted is a separate issue, the color being black instead of blue is what this issue is about. I still plan to work on it but am still busy, so no eta.

**Comment by RaphaelSantiago53** [comment]
In case anyone intends to implement this, I found a situation where it breaks. So unless they're able to account for it, I don't think this should be added.

When the code encapsulated by `\class{math-cloze}{ ... }` does not have a common and exclusive parent element in the rendered output (so no valid target for the class), it produces an error.

For example, this is a valid cloze card that currently produces no errors:
```latex
\begin{align}
  (5 - 11i) + (7 + 4i) &= {{c1:: (5 + 7) + (-11 + 4)i \\
                       &= 12 - 7i }}
\end{align}
```

This however is not valid and produces an error:
```latex
\begin{align}
  (5 - 11i) + (7 + 4i) &= \class{math-cloze}{ (5 + 7) + (-11 + 4)i \\
                       &= 12 - 7i }
\end{align}
```

But it can be fixed by using multiple `\class{math-cloze}{ ... }` like so:
```latex
\begin{align}
  (5 - 11i) + (7 + 4i) &= \class{math-cloze}{ (5 + 7) + (-11 + 4)i } \\
                       &\class{math-cloze}{= 12 - 7i }
\end{align}
```

**Comment by dae** [comment]
Thanks, that's helpful to know. It sounds like this may not be practical to implement.
