### ISSUE TITLE
When user selects a field that can't be sorted on, they get stuck on it

### ISSUE THREAD

**Issue by dae** [ankitects/anki#2701]
https://forums.ankiweb.net/t/anki-23-10-beta/34912/104

When they attempt to select a different field, it tries to refresh the current search (via call_after_note_saved) and fails, and the config remains set to the invalid value. Maybe we should a) have a new protobuf method to set the desired sort order, that can error out if it's invalid, and b) in the case of an invalid config, fall back to the default sort order instead of throwing an error?

@RumovZ if you think you'll have time to tackle this in the next week please do (asking you first since this is code you wrote); if you're busy, please let us know and I'll see if @abdnh would like to tackle it.

In the short term, users can work around it with

`mw.col.set_config("noteSortType", "noteFld")`

**Comment by user1823** [comment]
If we consider the specific example of the retrievability of a note, in the helper add-on, we take the retrievability of a note to be the (arithmetic) mean of the retrievabilities of all its cards. For the purpose of calculating the retrievability of a note, the retrievability for new cards is taken as zero.

Can we use the same approach to calculate the retrievability of a note in Anki's browser?

**Comment by RumovZ** [comment]
Should be able to look into this until next week.

**Comment by RumovZ** [comment]
It looks like the main problem is that you end up in an inconsistent state if the search during a state transition fails. More precisely, this leads to the table and the model having different states. And since you never properly move to the new state you can't fix its configuration.
In this instance, notes mode has an invalid sort column, which prevents the user from properly switching to it, which means they can't change the note sort column.

I see three layers to this issue, which need to be resolved in different ways:

1. `Column`s were designed to be sortable or not, independent of state. `BrowserColumns.Sorting` needs to be extended by something like `SORTING_CARDS` (and probably `SORTING_NOTES` while we're at it) to meet the new requirements.
2. Errors during state transition must be handled to avoid inconsistent states.
3. Configured sort orders must be validated so that bad values don't block the table set-up.

I don't see the benefit of a protobuf method for setting the sort order, because there could still be a bad config, or an add-on could decide to pass a sort order different from the configured one. The backend is already exposing valid options through the `Column` API.
