### ISSUE TITLE
ModuleNotFoundError: No module named 'google.protobuf'

### ISSUE THREAD

**Issue by sbhal** [ankitects/anki#2794]
```
❯ /Applications/Anki.app/Contents/MacOS/anki --version
Anki starting...
Initial setup...
Preparing to run...
Anki 23.10
```

```
❯ /Applications/Anki.app/Contents/MacOS/anki --syncserver
Anki starting...
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "aqt", line 24, in <module>
  File "anki.syncserver", line 9, in run_sync_server
  File "anki._backend", line 14, in <module>
  File "anki.backend_pb2", line 5, in <module>
ModuleNotFoundError: No module named 'google.protobuf'
```

```
❯ sw_vers
ProductName:            macOS
ProductVersion:         13.4
BuildVersion:           22F66
```

Anki is running fine with GUI but its a issue only when starting sync server.

**Comment by dae** [comment]
Thanks for letting me know. A temporary workaround you can use until the next patch update is to enter in the following:

% ANKI_STARTUP_REPL=1 /Volumes/Anki/Anki.app/Contents/MacOS/anki              
Anki starting...
Initial setup...
Python 3.9.15 (main, Nov  6 2022, 11:31:59) 
[Clang 14.0.3 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> from aqt.package import _fix_protobuf_path as f; f(); from anki.syncserver import run_sync_server as r; r()
Sync server failed: unable to create server

Caused by this error:
  1: No users defined; SYNC_USER1 env var should be set.
