### ISSUE TITLE
Deck names are duplicated when a CSV import uses a different case for the deck name

### ISSUE THREAD

**Issue by dae** [ankitects/anki#2951]
https://forums.ankiweb.net/t/importing-with-deck-column-create-many-decks-unstead-of-one/39566

**Comment by vaxr** [comment]
### Analysis

When importing a foreign card, a deck is either retrieved or created:

https://github.com/ankitects/anki/blob/0291847712fda23dec221b4e5bebd4a0178991bf/rslib/src/import_export/text/import.rs#L262-L274

The deck is retrieved from `DeckIdsByNameOrId`, which is case sensitive:

https://github.com/ankitects/anki/blob/0291847712fda23dec221b4e5bebd4a0178991bf/rslib/src/import_export/text/import.rs#L165-L171

Having found nothing, a new deck is created. The function handling this is case insensitive when checking for parent decks:

https://github.com/ankitects/anki/blob/0291847712fda23dec221b4e5bebd4a0178991bf/rslib/src/decks/addupdate.rs#L110-L114

My first impulse was to make `DeckIdsByNameOrId` case insensitive, but that addresses only part of the problem, and only partially fixes the bug.


### Conclusion

Case sensitivity for deck names isn't applied consistently.

What are Anki's deck naming rules?
- Should two names which differ in case only be disallowed? (In that case, how would we handle existing collections?)
- Should we allow it and be as tolerant as possible with case sensitivity when reading data, but stick to the original deck name when writing?

I'm considering taking some time to familiarize myself with how this issue is currently handled throughout the code base, so we can work on a comprehensive solution.

Please let me know if that would be helpful.

**Comment by dae** [comment]
UniCase is used at the DB level to ensure names don't only differ by case. My first guess is that we may want to switch self.names from a String to UniCase, but I haven't dug into the code yet. Rumo has worked with this part of the code the most and may have a preference for how this is tackled. @RumovZ, any thoughts?

**Comment by RumovZ** [comment]
No preference from my side. Whatever's easiest!
