### ISSUE TITLE
Add Deck Hide/Unhide

### ISSUE THREAD

**Issue by ahmedyarub** [ankitects/anki#3173]
Add a button in the gears menu to hide/unhide a deck, and a toggle to show hidden decks to be able to see and unhide hidden decks when required.

**Comment by dae** [comment]
Hi Ahmed,

I appreciate you taking the time to submit a well-written PR instead of just making a feature request, but I'm afraid I don't really see the demand for this feature. It's not something that has been frequently requested in the past, so I'm not sure the extra code and chance of possible bugs/regressions can be justified at this time. Sorry to be the bearer of bad news.

If you have other features in mind in the future, please post about them on the suggestions section of the forums, and indicate that you're willing to submit a PR. Then please wait until you've received a reply, as I don't want your hard work to go to waste.

**Comment by dae** [comment]
You've raised the subject on the forums, so let's continue conversation there.
