### ISSUE TITLE
Optimizing FSRS parameters shows 0 reviews

### ISSUE THREAD

**Issue by user1823** [ankitects/anki#3242]
<img width=500 src="https://github.com/ankitects/anki/assets/92206575/7f9099a7-e711-49a7-8005-50c3ca2804d2">

However, sometimes, it does show the correct count too.
<img width=500 src="https://github.com/ankitects/anki/assets/92206575/6404d7e1-ac4d-437f-aef3-4ab244dcaefe">

Test file: [Test.apkg.zip](https://github.com/user-attachments/files/15902832/Test.apkg.zip) (Rename to remove .zip)

In this file, try to optimize the parameters of the deck B (subdeck of A) to reproduce the issue.

**Comment by user1823** [comment]
I imported the apkg into a fresh profile and I was able to reproduce it a few times. The issue seems to appear randomly. 

However, I have reasons to think that the issue is more likely to be reproduced when the optimization finishes too fast. 

For e.g., if I start a screen recording, the CPU usage increases and the laptop becomes slightly slower and I am almost never able to reproduce the issue.

**Comment by benasocj** [comment]
I experience the same issue.

In the following scenarios the parameters have always been optimized already. For this reason the "...appear to be optimal" popup is always shown (which is expected).

Following scenarios I have come across:

### 1. Only "0 reviews" shown

Popup is shown:
![screenshot_count_zero1](https://github.com/user-attachments/assets/34f46d21-a82b-4f5b-a973-6745971841bf)
After I close the popup:
![screenshot_count_zero2](https://github.com/user-attachments/assets/a512116a-7b7d-4771-a103-d2ef1e62f2d2)

### 2. Only "1,896 reviews" shown

Popup is shown:
![screenshot_count_only1](https://github.com/user-attachments/assets/2a355ae8-f82b-48ce-b4c3-a761958038d0)
After I close the popup:
![screenshot_count_only2](https://github.com/user-attachments/assets/a437a409-2102-4ddb-af2c-255360fb897f)

### 3. "1,896 reviews" shown along with random percentage

Popup is shown, however with "1,896 reviews" and a random percentage already shown in the background (sometimes 60%, 58.6% or 49.3%):
![screenshot_percent_and_count1](https://github.com/user-attachments/assets/7a8087de-939a-4930-bcd8-511b10ef11cd)
![screenshot_percent_and_count2](https://github.com/user-attachments/assets/57a0bda4-942e-4c8b-a3fd-2142f956b084)
![screenshot_percent_and_count3](https://github.com/user-attachments/assets/5f9bbf99-a616-4c49-8059-f366be89d32b)
After I close the popup:
![screenshot_percent_and_count9](https://github.com/user-attachments/assets/c017e4f5-8f50-476a-9c52-ba207584b854)

As @user1823 has mentioned already, this really seems to happen due to a race condition. My laptop is running on a 14 year old CPU which may make it more likely for this race condition to occur.

**Environment**
- Anki version: 24.06.3
- OS: Debian GNU/Linux

**Comment by brishtibheja** [comment]
Not seeing the percentages is weirder. You are supposed to see the percentage rise to 100 per cent as the optimisation completes.

**Comment by dae** [comment]
I suspect that the progress update notifications are arriving asynchronously, and one or more is arriving after the operation has fully completed. Perhaps we could fix it by:

- in computeWeights(), using the returned reviews number, which is currently ignored in favor of the reviews listed in the progress messages
- hiding progress once the total reviews number has been returned
