### ISSUE TITLE
Cannot Add Quotation Marks in Deck Name

### ISSUE THREAD

**Issue by brishtibheja** [ankitects/anki#3252]
### Steps to reproduce

1. Use the Ditto mark (") in a deck name.
2. Save the deck.

### Expected behaviour

Deck appears with correct name.

### Actual behaviour

Quotation marks are removed from deck name upon save.

### Additional info

1. This behaviour isn't relroducible for other quotation marks (`“”`, `«»`).

**Comment by bpnguyen107** [comment]
I looked into this issue and it looks like the current code explicitly strips any ditto marks from the deck name here:

https://github.com/ankitects/anki/blob/f2adf5d9ad93b910e6954c27d8533c572706b189/rslib/src/decks/name.rs#L190-L198

@dae Do you know if there was a reason for that? Otherwise, I can open a pull request with the fix if we want to start showing ditto marks in deck names.
