### ISSUE TITLE
Update Docker container to 24.06.3

### ISSUE THREAD

**Issue by update-freak** [ankitects/anki#3271]
@jeankhawand Would be great if you could update the docker container to v24.06.3 on Dockerhub:
https://hub.docker.com/r/jeankhawand/anki-sync-server
Thanks a lot.

https://github.com/ankitects/anki/pull/3036

**Comment by jeankhawand** [comment]
Hello @update-freak, Thank you for raising this issue. After reviewing the release notes and changes, there were no modifications made to the sync server. I should have used a server-specific semantic version instead of coupling it with the core libraries. Therefore, we will remain on version 24.04.1.

**Comment by update-freak** [comment]
All right, thanks for checking and the quick reply.
Then I will close this issue.
