### ISSUE TITLE
Feat Daily load and retention by notes stats

### ISSUE THREAD

**Issue by filipenanclarez** [ankitects/anki#3446]
Fine. I added the Estimated total knowledge (cards):

<img width="833" alt="image" src="https://github.com/user-attachments/assets/076e90cb-334f-4cce-967e-0f55f3feb944">

Daily load and retention by notes require more works to do, so I will consider it in another PR.

_Originally posted by @L-M-Sherlock in https://github.com/ankitects/anki/issues/3425#issuecomment-2365992087_

**Comment by Expertium** [comment]
@L-M-Sherlock suggestions
1) Estimated total knowledge should be an integer
2) Use the description from the add-on: "the number of cards the user is expected to know today, calculated as the product of average predicted retention and count."
3) Add Daily Load, Total Count, Total Time and the most interesting one, Knowledge acquisition rate. All with their respective descriptions.
![image](https://github.com/user-attachments/assets/b28fb3bf-28aa-4a05-9476-0ced3a8f70c0)

@dae this will add a lot of new numbers, and also a lot of text, which is something that native Anki stats didn't have until now, as they were self-explanatory enough. This may seem excessive, but I doubt that users will be able to figure out what "Daily Load", let alone "Estimated total knowledge" and "Knowledge acquisition rate" means without any hints. So first I'd like to confirm that you are not against adding interpretations, and also I want to ask where should all of this be put. I feel like we need a new "FSRS" section in the Stats for FSRS-related stats, though that still leaves Daily Load, idk where to put that one.

**Comment by brishtibheja** [comment]
> "the number of cards the user is expected to know today, calculated as the product of average predicted retention and count."

The calculation part seems totally unnecessary. The median user isn't very interested in the math part.

> Add Daily Load, Total Count, Total Time and the most interesting one, Knowledge acquisition rate. All with their respective descriptions.

Total count is already shown in Card Counts. Daily load should be figurable from "Future due" graph.

**Comment by filipenanclarez** [comment]
> > "the number of cards the user is expected to know today, calculated as the product of average predicted retention and count."
> 
> The calculation part seems totally unnecessary. The median user isn't very interested in the math part.
> 
> > Add Daily Load, Total Count, Total Time and the most interesting one, Knowledge acquisition rate. All with their respective descriptions.
> 
> Total count is already shown in Card Counts. Daily load should be figurable from "Future due" graph.

I totally disagree 

My students use this number to monitor progress because we use language decks with many siblings.

This information is very relevant for us.

**Comment by brishtibheja** [comment]
That comment was meant to be for the descrip. of Estimated knowledge.

**Comment by dae** [comment]
My preference would be to add only the most useful/popular info from the add-on, and see how much demand there is for the remaining items over time. Anything we do add will of course require documentation/tooltips. I don't think we should be trying to describe each of those options directly inside the page (e.g. via subheadings), as it will make things too noisy.

**Comment by Expertium** [comment]
> My preference would be to add only the most useful/popular

Well, we have no way of knowing which of these are popular or not, so idk what to say.

> I don't think we should be trying to describe each of those options directly inside the page (e.g. via subheadings)

Then how?

**Comment by Expertium** [comment]
@dae
Ok, here are the results: https://docs.google.com/forms/d/1PnVpddW7YtMLEZIWzk1mL04sJFxC4DmcQsd4GiaRX90/viewanalytics

For each entry I will count everything that's not a "Yes" as "Not yes" and use `scipy.stats.binomtest` to determine whether the ratio is significantly different from 50%.
**Daily Load**: 76% "Yes", 24% "Not yes", p-value=2E-04. Conclusion: people want Daily Load.
**Total Time**: 47% "Yes", 53% "Not yes", p-value=0.78. Conclusion: inconclusive.
**Estimated Total Knowledge**: 67% "Yes", 33% "Not yes", p-value=0.02. Conclusion: people want Estimated Total Knowledge.
**Knowledge Acquisition Rate**: 55% "Yes", 45% "Not yes", p-value=0.58. Conclusion: inconclusive.
Text descriptions: 45% "Yes", 55% "Not yes", p-value=0.58. Conclusion: inconclusive.

I think instead of adding text descriptions directly, we could make them appear when the user hovers the mouse over the stat. Though idk how that would work on mobile. Alternative solution: make the stats themselves hyperlinks that lead to the manual where we'll add descriptions. So if the user taps/clicks a stat that says "Knowledge Acquisition Rate", a browser page will open.

P.S. for the sake of achieving parity with the Helper add-on, let's exclude suspended and deleted cards from the calculation of average difficulty, stability and retrievability, and from the calculation of the new stats, too.

**Comment by dae** [comment]
Surveys have their uses, but when you give users the option of selecting as many items as they want, I think you end up with a list of "yeah, that might be cool", instead of a list of features that users are really missing.

That said, I appreciate you taking the time to put it together, and I'm glad to see we can at least consider dropping the three inconclusive ones for now.

There's no hover action on mobile, so it would need to respond to a tap instead. One option would be to have the text tappable to open a manual entry, like we do with the deck options.
