### ISSUE TITLE
Deck option changes not detected until focus is lost

### ISSUE THREAD

**Issue by dae** [ankitects/anki#3472]
Originally reported on https://forums.ankiweb.net/t/anki-24-10-beta/49989/6

> When closing the Deck Options screen, the Discard changes? dialog is not shown if changes were made only by directly interacting with an input field (either using the keyboard or the mouse, but not through UI buttons).

Currently the Python code is expecting a synchronous return from deckOptionsPendingChanges(), so we can't just throw in an await tick(). We might need to switch to using a bridge command or similar instead.

**Comment by dae** [comment]
@Arthur-Milchior heads up, in case you feel like tackling this

**Comment by Arthur-Milchior** [comment]
That's frustrating. The state is updated only on `blur` which is async operation. So forcing `blur` from python is a bad idea. Unless, once blur is done, the js sends a pycmd to python to tell it to close. That can be done, but seems uselessly complex for such a bug.

Checking whether the currently active element had changed since its initialization does not seems easily doable, since this element is a basic HTML input element, which don't store its default value.

Updating the state each time the value change would be more costly. Probably acceptable on any device today, but that's not elegant. And worse, it would require to change a lot of input field so that instead of `on:blur` it actually listen to change in the input value
