### ISSUE TITLE
Can't Select Deck in Stats Screen (Mobile)

### ISSUE THREAD

**Issue by brishtibheja** [ankitects/anki#3595]
## Steps

1. Open stats screen
2. Select `collection`
3. Try switching back to `deck`

### Expected behaviour

switches back to `deck`

### Actual behaviour

Clicking there doesn't work most of the times. To switch back to `deck` it sometimes take 3-4 clicks. This doesn't happen anywhere else in the same screen.

___

Was asked to report it here. Originally posted in https://github.com/ankidroid/Anki-Android/issues/16459.

**Comment by dae** [comment]
A quick check with the inspector shows it's the invisible but still-rotating progress spinner that's catching the clicks. Adjusting the z-index of the radio buttons or decreasing the font size would likely fix it. As far as I'm aware, AnkiMobile is unaffected due to a smaller font size. As it's an AD-specific issue, I'd like an AD dev or user to submit a PR for this, as it's a good introduction into fixing AD-specific issues.

To reproduce with a computer, use `ANKI_API_PORT=8000 ./run` to start Anki, surf to http://localhost:8000/graphs, increase the font size, and reduce the width of the window.

**Comment by mikehardy** [comment]
Carried that info into our ankidroid-dev channel on Discord - with a local reproduction and a reasonable handle on the issue it does look like a "good first issue". Not sure if you have an "AnkiDroid" (or AnkiDroid-specific or whatever makes sense) label in this repo, but if you did and you tagged these up it could form a queue to scan periodically. Otherwise I fear it'll get lost in the low-priority shuffle and even people hunting for good first issues might never see it

**Comment by Sawansunar56** [comment]
Can I work on this?
